# -*- coding: utf-8 -*-
"""Binary_CIC_DDoS19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pvCurwRr_zl3Oja-d4imT4oSAnn9sH2B
"""

# STEP 1: Import Libraries
# ==========================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

import warnings
warnings.filterwarnings('ignore')

# =========================================
# STEP 2: MOUNT GOOGLE DRIVE AND LOAD DATA
# =========================================

from google.colab import drive
import os
import pandas as pd

# Mount Google Drive
drive.mount('/content/drive')

# Path to your dataset folder
data_path = '/content/drive/MyDrive/CIC_19/'

# List all files in the folder
files = os.listdir(data_path)
print("📁 Files in dataset folder:", files)

# Try loading Parquet first
df_list = []
for f in files:
    if f.endswith('.parquet'):
        file_path = os.path.join(data_path, f)
        print("📄 Loading Parquet file:", f)
        temp_df = pd.read_parquet(file_path)
        df_list.append(temp_df)

# If Parquet files are found, combine them
if len(df_list) > 0:
    df = pd.concat(df_list, ignore_index=True)
    print("✅ Loaded Parquet dataset successfully.")
    print("Shape:", df.shape)
    print("🔍 Columns:", df.columns[:10].tolist(), "...")
else:
    # Fall back to CSV if no Parquet found
    csv_files = [f for f in files if f.endswith('.csv')]
    if len(csv_files) == 0:
        raise ValueError("⚠️ No Parquet or CSV files found in the folder.")
    csv_path = os.path.join(data_path, csv_files[0])
    print(f"📄 Loading CSV file: {csv_files[0]}")
    df = pd.read_csv(csv_path)
    print("✅ Loaded CSV dataset successfully.")
    print("Shape:", df.shape)
    print("🔍 Columns:", df.columns[:10].tolist(), "...")

# =============================================
# STEP 2 — Preprocessing (Cleaning & Encoding)
# =============================================

from sklearn.preprocessing import LabelEncoder

# Copy dataset
data = df.copy()

# Drop columns with all null values (if any)
data.dropna(axis=1, how='all', inplace=True)

# Handle NaN or infinite values
data.replace([np.inf, -np.inf], np.nan, inplace=True)
data.dropna(inplace=True)

# Identify the label column
# Update this if your column name differs (check df.columns)
label_col = "Label"

# Encode labels (e.g., "BENIGN" → 0, "DrDoS_DNS" → 1, etc.)
le = LabelEncoder()
data[label_col] = le.fit_transform(data[label_col])

# Separate features and target
X = data.drop(columns=[label_col])
y = data[label_col]

print("✅ Preprocessing done!")
print(f"Features shape: {X.shape}")
print(f"Target classes: {list(le.classes_)}")

df = df.copy()

df['Label'] = df['Label'].astype(str).str.strip()

df['binary_label'] = df['Label'].apply(lambda x: 0 if x == 'Benign' else 1)

print(df['binary_label'].value_counts())

from sklearn.model_selection import train_test_split

X = df.drop(columns=['Label', 'binary_label'])
y = df['binary_label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

print("Train:", X_train.shape, " Test:", X_test.shape)

from sklearn.feature_selection import mutual_info_classif
import pandas as pd

mi_scores = mutual_info_classif(X_train, y_train)
mi_series = pd.Series(mi_scores, index=X_train.columns)

# select top k filter features
k = 40
filter_features = mi_series.sort_values(ascending=False).head(k).index.tolist()

print("Mutual Info selected:", len(filter_features))

!pip install deap

from deap import base, creator, tools
import random
import numpy as np
from sklearn.model_selection import cross_val_score
import lightgbm as lgb

search_features = filter_features
N_FEATURES = len(search_features)

# GA fitness maximize
creator.create("FitnessMax", base.Fitness, weights=(1.0,))
creator.create("Individual", list, fitness=creator.FitnessMax)

toolbox = base.Toolbox()

# chromosome genes = 0/1 (feature on/off)
toolbox.register("attr_bool", lambda: random.randint(0, 1))
toolbox.register("individual", tools.initRepeat, creator.Individual,
                 toolbox.attr_bool, N_FEATURES)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

def evaluate(individual):
    selected = [search_features[i] for i in range(N_FEATURES) if individual[i] == 1]
    if len(selected) == 0:
        return 0.0,  # avoid empty subset

    X_sub = X_train[selected]

    model = lgb.LGBMClassifier(
        n_estimators=200,
        learning_rate=0.05,
        max_depth=-1,
        num_leaves=31,
        n_jobs=-1
    )

    score = cross_val_score(model, X_sub, y_train, cv=3, scoring="f1").mean()
    return score,

toolbox.register("evaluate", evaluate)
toolbox.register("mate", tools.cxTwoPoint)
toolbox.register("mutate", tools.mutFlipBit, indpb=0.05)
toolbox.register("select", tools.selTournament, tournsize=3)

POP_SIZE = 20
N_GEN = 10

population = toolbox.population(n=POP_SIZE)

for gen in range(N_GEN):
    print(f"\n📌 Generation {gen+1}/{N_GEN}")

    offspring = toolbox.select(population, len(population))
    offspring = list(map(toolbox.clone, offspring))

    for c1, c2 in zip(offspring[0::2], offspring[1::2]):
        if random.random() < 0.7:
            toolbox.mate(c1, c2)
            del c1.fitness.values
            del c2.fitness.values

    for mutant in offspring:
        if random.random() < 0.2:
            toolbox.mutate(mutant)
            del mutant.fitness.values

    invalid = [ind for ind in offspring if not ind.fitness.valid]
    fitnesses = map(toolbox.evaluate, invalid)
    for ind, fit in zip(invalid, fitnesses):
        ind.fitness.values = fit

    population[:] = offspring
    best = tools.selBest(population, 1)[0]

    print("⭐ Best F1:", round(best.fitness.values[0], 4))

best_ind = tools.selBest(population, 1)[0]
ga_features = [search_features[i] for i in range(N_FEATURES) if best_ind[i] == 1]

print("\n🔥 FINAL GA Selected Features:", len(ga_features))
print(ga_features)

X_train_sel = X_train[ga_features]
X_test_sel  = X_test[ga_features]

from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state=42)
X_train_bal, y_train_bal = sm.fit_resample(X_train_sel, y_train)

print("After SMOTE:", X_train_bal.shape)
print(y_train_bal.value_counts())

final_lgbm = lgb.LGBMClassifier(
    n_estimators=500,
    learning_rate=0.05,
    num_leaves=40,
    max_depth=-1,
    n_jobs=-1
)

final_lgbm.fit(X_train_bal, y_train_bal)
from sklearn.metrics import classification_report, confusion_matrix

y_pred = final_lgbm.predict(X_test_sel)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4))

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=400,
    max_depth=25,
    min_samples_split=2,
    min_samples_leaf=1,
    class_weight=None,   # because we already used SMOTE
    n_jobs=-1,
    random_state=42
)

rf.fit(X_train_bal, y_train_bal)
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

y_pred = rf.predict(X_test_sel)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred, digits=4))
y_prob = rf.predict_proba(X_test_sel)[:, 1]
auc = roc_auc_score(y_test, y_prob)

print("\nROC-AUC Score:", auc)

import xgboost as xgb

xgb_model = xgb.XGBClassifier(
    n_estimators=500,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.9,
    colsample_bytree=0.9,
    gamma=0,
    reg_lambda=1,
    objective='binary:logistic',
    tree_method="hist",   # fastest on large datasets
    n_jobs=-1,
    random_state=42
)

xgb_model.fit(X_train_bal, y_train_bal)
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

y_pred = xgb_model.predict(X_test_sel)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred, digits=4))
y_prob = xgb_model.predict_proba(X_test_sel)[:, 1]
auc = roc_auc_score(y_test, y_prob)

print("\nROC-AUC Score:", auc)

!pip install catboost

from catboost import CatBoostClassifier

cat_model = CatBoostClassifier(
    iterations=600,
    learning_rate=0.05,
    depth=8,
    loss_function='Logloss',
    eval_metric='F1',
    random_seed=42,
    verbose=100,       # shows progress every 100 iters
    thread_count=-1
)

cat_model.fit(X_train_bal, y_train_bal)
from sklearn.metrics import classification_report, confusion_matrix

y_pred = cat_model.predict(X_test_sel)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred, digits=4))
from sklearn.metrics import roc_auc_score

y_prob = cat_model.predict_proba(X_test_sel)[:, 1]
auc = roc_auc_score(y_test, y_prob)

print("\nROC-AUC Score:", auc)