# -*- coding: utf-8 -*-
"""Binary_UNSW_NB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NmCY3kofcZ7fXBWuWllAFatsGndqfNN8
"""

# ==========================
# STEP 1: Import Libraries
# ==========================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

import warnings
warnings.filterwarnings('ignore')

# =========================================
# STEP 2: MOUNT GOOGLE DRIVE AND LOAD UNSW-NB15 DATA
# =========================================
from google.colab import drive
import os
import pandas as pd

# Mount Google Drive
drive.mount('/content/drive')

# Path to your dataset folder
data_path = '/content/drive/MyDrive/UNSW_NB/'

# List all files inside the folder
files = os.listdir(data_path)
print("📁 Files in dataset folder:", files)

# The UNSW-NB15 dataset usually has multiple CSV files:
# e.g., 'UNSW_NB15_training-set.csv', 'UNSW_NB15_testing-set.csv'
train_file = [f for f in files if 'training' in f.lower()][0]
test_file = [f for f in files if 'testing' in f.lower()][0]

# Load the CSV files
print(f"📄 Loading training set: {train_file}")
train_df = pd.read_csv(os.path.join(data_path, train_file))

print(f"📄 Loading testing set: {test_file}")
test_df = pd.read_csv(os.path.join(data_path, test_file))

# Combine them (optional but often useful for feature engineering)
df = pd.concat([train_df, test_df], ignore_index=True)

print("✅ Dataset loaded successfully.")
print("Shape:", df.shape)
print("\n🔍 Columns:", df.columns[:40].tolist(), "...")
print("\n🎯 Target column samples:", df[['label', 'attack_cat']].head())

# =========================================
# STEP 3: DATA PREPROCESSING
# =========================================
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Drop 'id' as it doesn't help with prediction
df = df.drop(columns=['id'], errors='ignore')

# Check for missing values
print("🧹 Missing values per column:\n", df.isnull().sum().sort_values(ascending=False).head())

# Fill missing categorical values with mode, numeric with median
for col in df.columns:
    if df[col].dtype == 'object':
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        df[col].fillna(df[col].median(), inplace=True)

# Identify categorical columns
cat_cols = ['proto', 'service', 'state']

# Encode categorical features
le = LabelEncoder()
for col in cat_cols:
    df[col] = le.fit_transform(df[col])

# Check encoding
print("\n🔢 Encoded categorical columns:", cat_cols)
print(df[cat_cols].head())

# Define features and target
X = df.drop(columns=['label', 'attack_cat'])
y_binary = df['label']          # For binary classification (Attack vs Normal)
y_multi = df['attack_cat']      # For multiclass classification (attack type)

# Encode multiclass target
y_multi = LabelEncoder().fit_transform(y_multi)

# Normalize numeric features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("\n✅ Preprocessing complete!")
print("Feature matrix shape:", X_scaled.shape)
print("Binary target shape:", y_binary.shape)
print("Multiclass target shape:", y_multi.shape)

## ===============================================================
# STEP 2 — HYBRID FEATURE SELECTION (OPTIMIZED GA v2) — UNSW-NB15
# ===============================================================
import numpy as np
import pandas as pd
import time, gc, joblib, random, os, warnings
from sklearn.feature_selection import mutual_info_classif
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier

warnings.filterwarnings('ignore')

# ------------------- CONFIG -------------------
RANDOM_STATE = 42
SUBSAMPLE = 100000           # ↑ slightly larger subset for GA → better generalization
FILTER_TOP = 40              # ↑ from 40 → more candidates for GA
POP_SIZE = 15                # ↑ larger population improves diversity
N_GEN = 15                  # ↑ more generations for convergence
MUT_RATE = 0.12              # ↓ slight decrease to maintain elite stability
KNN_FIT_K = 7              # better local smoothness for UNSW-NB15
KNN_FIT_CV = 3               # 3-fold CV for more robust fitness
TOP_FINAL = 30               # ↑ to get top 30 hybrid-selected features
SAVE_PATH = "/content/drive/MyDrive/UNSW_NB15"
os.makedirs(SAVE_PATH, exist_ok=True)

# Choose which target to use:
# y_binary → Attack vs Normal
# y_multi  → Attack category
y = y_binary   # or y_multi
# ------------------------------------------------

print("Preparing optimized GA data (v2)...")

# ✅ Convert X_scaled to DataFrame if it’s a NumPy array
if isinstance(X_scaled, np.ndarray):
    X_df = pd.DataFrame(X_scaled, columns=[f"f{i}" for i in range(X_scaled.shape[1])])
else:
    X_df = X_scaled.copy()

y_arr = np.array(y)
feature_names = list(X_df.columns)

# --- Subsample for GA ---
rng = np.random.default_rng(RANDOM_STATE)
sel_idx = rng.choice(X_df.shape[0], size=min(SUBSAMPLE, X_df.shape[0]), replace=False)
X_sub_df = X_df.iloc[sel_idx].reset_index(drop=True)
y_sub = y_arr[sel_idx]
X_sub = X_sub_df.values.astype(np.float32)
print(f"Subsampled shape for GA: {X_sub.shape}")

# --- Filter stage (Mutual Information) ---
print("\n[1] Filter Stage: Mutual Information (top {})".format(FILTER_TOP))
mi = mutual_info_classif(X_sub, y_sub, random_state=RANDOM_STATE)
mi_series = pd.Series(mi, index=feature_names)
selected_filter = mi_series.sort_values(ascending=False).head(FILTER_TOP).index.tolist()
print(f"Top-{FILTER_TOP} features:\n{selected_filter}\n")
X_filt = X_sub[:, [feature_names.index(f) for f in selected_filter]].astype(np.float32)

# --- GA stage (Optimized) ---
print("[2] Genetic Algorithm Optimization — please wait (20 gens, ~30 min)...")
random.seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)

# Use StratifiedKFold for more stable accuracy
cv_strategy = StratifiedKFold(n_splits=KNN_FIT_CV, shuffle=True, random_state=RANDOM_STATE)

def knn_fitness_mask(mask):
    cols = [i for i, b in enumerate(mask) if b]
    if not cols:
        return 0.0
    Xtmp = X_filt[:, cols]
    knn = KNeighborsClassifier(n_neighbors=KNN_FIT_K)
    try:
        scores = cross_val_score(knn, Xtmp, y_sub, cv=cv_strategy, scoring='accuracy', n_jobs=-1)
        return float(scores.mean())
    except Exception:
        return 0.0

n_feat = len(selected_filter)
pop = [np.random.randint(0, 2, n_feat).astype(np.int8) for _ in range(POP_SIZE)]
best_mask, best_score = None, -1

for g in range(1, N_GEN + 1):
    fitness = np.array([knn_fitness_mask(ind) for ind in pop], dtype=np.float32)
    gen_best = fitness.max()
    gen_mean = fitness.mean()
    if gen_best > best_score:
        best_score = gen_best
        best_mask = pop[int(np.argmax(fitness))].copy()
    print(f"Gen {g:02d}/{N_GEN}: best={gen_best:.4f}, mean={gen_mean:.4f}")

    # Selection: roulette + elitism
    elite_idx = np.argmax(fitness)
    elites = [pop[elite_idx].copy()]
    probs = np.maximum(fitness, 1e-6)
    probs = probs / probs.sum()
    new_pop = elites.copy()
    while len(new_pop) < POP_SIZE:
        p1, p2 = random.choices(pop, weights=probs, k=2)
        cx = np.random.randint(1, n_feat - 1)
        c1 = np.concatenate([p1[:cx], p2[cx:]])
        c2 = np.concatenate([p2[:cx], p1[cx:]])
        for c in (c1, c2):
            r = np.random.random(size=c.shape)
            c[r < MUT_RATE] = 1 - c[r < MUT_RATE]
            new_pop.append(c.astype(np.int8))
    pop = new_pop[:POP_SIZE]
    gc.collect()

print(f"\n✅ GA completed. Best KNN fitness score = {best_score:.4f}")
sbm_selected = [selected_filter[i] for i, b in enumerate(best_mask) if b == 1]
print(f"SBM-selected {len(sbm_selected)} features:\n{sbm_selected}")

# --- RFR ranking on GA-selected features ---
print("\n[3] RandomForest Ranking...")
X_rfr = X_sub_df[sbm_selected].values.astype(np.float32)
rfr = RandomForestClassifier(
    n_estimators=400,       # ↑ more trees for stability
    max_depth=None,
    max_features='sqrt',    # ↓ avoids overfitting
    min_samples_split=4,    # ↓ helps generalize
    random_state=RANDOM_STATE,
    n_jobs=-1
)
rfr.fit(X_rfr, y_sub)
imp = pd.Series(rfr.feature_importances_, index=sbm_selected).sort_values(ascending=False)
final_features = imp.head(TOP_FINAL).index.tolist()
print(f"\n🔥 Final {TOP_FINAL} hybrid-selected features:\n{final_features}")

# --- Save final feature list ---
save_file = os.path.join(SAVE_PATH, "final_hybrid_features_UNSWNB15_OPTGA_v2.pkl")
joblib.dump(final_features, save_file)
print(f"\n💾 Saved improved GA feature list to: {save_file}")

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# ✅ Train Random Forest
rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train_res, y_train_res)

# ✅ Predictions
y_pred = rf.predict(X_test)

# ✅ Evaluation
print("\n🎯 Random Forest Evaluation:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

import joblib
joblib.dump(rf, "UNSW_RF_model.pkl")
print("Model saved ✅")

import joblib, json

# Assuming your trained RF model is stored in variable 'rf'
rf_model_path = "/content/drive/MyDrive/UNSW_NB15/rf_binary_UNSWNB15.pkl"
rf_results_path = "/content/drive/MyDrive/UNSW_NB15/rf_binary_results.json"

# Save the model
joblib.dump(rf, rf_model_path)
print(f"💾 Model saved to: {rf_model_path}")

# Example: Save accuracy/F1 or other metrics (replace with your actual variables)
results = {
    "Accuracy": 0.9501,
    "Weighted_F1": 0.9493,
    "Training_Time_sec": 34.52
}

with open(rf_results_path, "w") as f:
    json.dump(results, f, indent=4)

print(f"💾 Results saved to: {rf_results_path}")

# ===============================================================
# STEP — Enhanced Random Forest for Multiclass UNSW-NB15
# ===============================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib, warnings, time
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    f1_score
)
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from imblearn.over_sampling import SMOTE

warnings.filterwarnings('ignore')

# -------------------
# 🧩 Load Hybrid-Selected Features
# -------------------
selected_features = joblib.load("/content/drive/MyDrive/UNSW_NB15/final_hybrid_features_UNSWNB15_OPTGA_v2.pkl")

# Assuming your data: X_scaled (preprocessed features), y_multi (labels)
X_df = pd.DataFrame(X_scaled, columns=[f"f{i}" for i in range(X_scaled.shape[1])])
X_selected = X_df[selected_features]

# -------------------
# 🔤 Encode Target Labels
# -------------------
le = LabelEncoder()
y_encoded = le.fit_transform(y_multi)
class_names = [str(c) for c in le.classes_]
print("Classes:", class_names)

# -------------------
# ⚖️ Train-Test Split
# -------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_selected, y_encoded, test_size=0.3, stratify=y_encoded, random_state=42
)

# -------------------
# ⚖️ Apply SMOTE for Class Balancing
# -------------------
sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

print("\nBefore SMOTE:\n", pd.Series(y_train).value_counts())
print("\nAfter SMOTE:\n", pd.Series(y_train_res).value_counts())

# -------------------
# ⚙️ Feature Scaling
# -------------------
scaler = StandardScaler()
X_train_res = scaler.fit_transform(X_train_res)
X_test = scaler.transform(X_test)

# -------------------
# 🌲 Optimized Random Forest
# -------------------
rf_multi = RandomForestClassifier(
    n_estimators=600,          # more trees = better generalization
    max_depth=40,              # control overfitting
    min_samples_split=3,
    min_samples_leaf=2,
    max_features='sqrt',
    class_weight='balanced',   # helpful for residual imbalance
    random_state=42,
    n_jobs=-1
)

# -------------------
# 🎯 Cross-validation before final training
# -------------------
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(rf_multi, X_train_res, y_train_res, cv=cv, scoring='accuracy', n_jobs=-1)
print(f"\n🔁 5-Fold CV Accuracy: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

# -------------------
# 🧠 Train Final Model
# -------------------
start = time.time()
rf_multi.fit(X_train_res, y_train_res)
end = time.time()
print(f"\n⏱️ Training Time: {end-start:.2f}s")

# -------------------
# 🔍 Prediction
# -------------------
y_pred = rf_multi.predict(X_test)

# -------------------
# 📈 Evaluation Metrics
# -------------------
acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
print(f"\n🎯 Random Forest (Multiclass) Evaluation:")
print(f"Accuracy: {acc:.4f}")
print(f"Weighted F1-Score: {f1:.4f}\n")

print("📋 Classification Report:")
print(classification_report(y_test, y_pred, target_names=class_names))

# -------------------
# 🧮 Confusion Matrix Visualization
# -------------------
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(10,8))
sns.heatmap(cm, annot=False, cmap='YlGnBu',
            xticklabels=class_names, yticklabels=class_names)
plt.title(f"Confusion Matrix — Random Forest (Acc={acc:.2f})")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

from lightgbm import LGBMClassifier
import time

print("\n🚀 Training LightGBM Multiclass Model...")

start = time.time()
lgb_model = LGBMClassifier(
    objective='multiclass',
    num_class=len(le.classes_),
    learning_rate=0.05,
    n_estimators=500,
    num_leaves=64,
    max_depth=-1,
    feature_fraction=0.8,
    bagging_fraction=0.8,
    bagging_freq=5,
    random_state=42,
    n_jobs=-1,
    verbose=-1  # suppress training logs
)

lgb_model.fit(X_train_res, y_train_res)
y_pred_lgb = lgb_model.predict(X_test)
end = time.time()

lgb_acc = accuracy_score(y_test, y_pred_lgb)
lgb_f1 = f1_score(y_test, y_pred_lgb, average='weighted')

print(f"✅ LightGBM Accuracy: {lgb_acc:.4f}, Weighted F1: {lgb_f1:.4f}, Time: {end-start:.2f}s")

# ===============================================================
# ⚡ LightGBM for Binary Classification — UNSW-NB15
# ===============================================================

import lightgbm as lgb
import pandas as pd
import numpy as np
import joblib, time, json
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.metrics import accuracy_score, classification_report, f1_score, confusion_matrix
from imblearn.over_sampling import SMOTE
import matplotlib.pyplot as plt
import seaborn as sns

# ---------------------------------------------------------------
# 🔹 Load hybrid-selected features
# ---------------------------------------------------------------
selected_features = joblib.load("/content/drive/MyDrive/UNSW_NB15/final_hybrid_features_UNSWNB15_OPTGA_v2.pkl")

# Assuming you already have these variables prepared:
# X_scaled → normalized numeric features
# y_binary → binary labels (0 = Normal, 1 = Attack)
X_df = pd.DataFrame(X_scaled, columns=[f"f{i}" for i in range(X_scaled.shape[1])])
X_selected = X_df[selected_features]

# ---------------------------------------------------------------
# 📚 Split dataset
# ---------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_selected, y_binary, test_size=0.3, stratify=y_binary, random_state=42
)

# ---------------------------------------------------------------
# ⚖️ Apply SMOTE to balance binary classes
# ---------------------------------------------------------------
sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

print("\nBefore SMOTE:", pd.Series(y_train).value_counts())
print("After SMOTE:", pd.Series(y_train_res).value_counts())

# ---------------------------------------------------------------
# 🚀 Train LightGBM Model
# ---------------------------------------------------------------
params = {
    "objective": "binary",
    "boosting_type": "gbdt",
    "metric": ["binary_error", "binary_logloss"],
    "learning_rate": 0.05,
    "num_leaves": 60,
    "max_depth": -1,
    "feature_fraction": 0.8,
    "bagging_fraction": 0.8,
    "bagging_freq": 5,
    "n_jobs": -1,
    "verbose": -1,
    "random_state": 42
}

train_data = lgb.Dataset(X_train_res, label=y_train_res)
test_data = lgb.Dataset(X_test, label=y_test, reference=train_data)

print("\n🚀 Training LightGBM Binary Model...")
start = time.time()
lgb_model = lgb.train(params, train_data, num_boost_round=500, valid_sets=[test_data])
end = time.time()

# ---------------------------------------------------------------
# 🎯 Evaluation
# ---------------------------------------------------------------
y_pred_prob = lgb_model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)

acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average="weighted")

print(f"\n✅ LightGBM Binary Accuracy: {acc:.4f}, Weighted F1: {f1:.4f}, Time: {end-start:.2f}s")

print("\n📋 Classification Report:\n", classification_report(y_test, y_pred))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.title("LightGBM Confusion Matrix — Binary UNSW-NB15")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# ---------------------------------------------------------------
# 💾 Save Model and Results
# ---------------------------------------------------------------
model_path = "/content/drive/MyDrive/UNSW_NB15/lgb_binary_UNSWNB15.pkl"
joblib.dump(lgb_model, model_path)

results = {
    "accuracy": float(acc),
    "weighted_f1": float(f1),
    "train_time_sec": round(end - start, 2),
    "features_used": selected_features,
}
with open("/content/drive/MyDrive/UNSW_NB15/lgb_binary_results.json", "w") as f:
    json.dump(results, f, indent=4)

print(f"\n💾 Model saved to: {model_path}")
print("💾 Results saved to: /content/drive/MyDrive/UNSW_NB15/lgb_binary_results.json")

# ===============================================================
# STEP — XGBoost Binary Classifier (UNSW-NB15)
# ===============================================================
import numpy as np
import pandas as pd
import xgboost as xgb
import time
from sklearn.metrics import classification_report, accuracy_score, f1_score
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
import joblib

# -------------------
# Load your hybrid-selected features
# -------------------
selected_features = joblib.load("/content/drive/MyDrive/UNSW_NB15/final_hybrid_features_UNSWNB15_OPTGA_v2.pkl")

# Assuming you have these already defined
# X_scaled → scaled full feature matrix
# y_binary → Attack vs Normal labels
X_df = pd.DataFrame(X_scaled, columns=[f"f{i}" for i in range(X_scaled.shape[1])])
X_selected = X_df[selected_features]

# -------------------
# Train-test split
# -------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_selected, y_binary, test_size=0.3, stratify=y_binary, random_state=42
)

# -------------------
# Apply SMOTE
# -------------------
print("Before SMOTE:", pd.Series(y_train).value_counts())
sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)
print("After SMOTE:", pd.Series(y_train_res).value_counts())

# -------------------
# Train XGBoost
# -------------------
print("\n🚀 Training XGBoost Binary Model...")
start = time.time()

xgb_model = xgb.XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=8,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.1,
    reg_lambda=1.0,
    random_state=42,
    n_jobs=-1,
    objective="binary:logistic",
    tree_method="hist"
)

xgb_model.fit(X_train_res, y_train_res, eval_set=[(X_test, y_test)], verbose=False)
end = time.time()

# -------------------
# Evaluate
# -------------------
y_pred = xgb_model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

print(f"\n✅ XGBoost Binary Accuracy: {acc:.4f}, Weighted F1: {f1:.4f}, Time: {end-start:.2f}s")
print("\n📋 Classification Report:\n", classification_report(y_test, y_pred))

# -------------------
# Save model + results
# -------------------
xgb_model.save_model("/content/drive/MyDrive/UNSW_NB15/XGBoost_UNSWNB15_binary.json")

results = pd.DataFrame({
    "Model": ["XGBoost"],
    "Accuracy": [acc],
    "Weighted_F1": [f1],
    "Train_Time_sec": [end - start]
})
results.to_csv("/content/drive/MyDrive/UNSW_NB15/XGBoost_UNSWNB15_results.csv", index=False)

print("\n💾 Model and results saved to Google Drive successfully!")

import joblib, json, time
from sklearn.metrics import accuracy_score, f1_score, classification_report

# -------------------
# 📊 Evaluate model (if not already done)
# -------------------
y_pred = xgb_model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

print(f"\n✅ XGBoost Binary Accuracy: {acc:.4f}, Weighted F1: {f1:.4f}")
print("\n📋 Classification Report:\n", classification_report(y_test, y_pred))

# -------------------
# 💾 Save paths
# -------------------
model_path = "/content/drive/MyDrive/UNSW_NB15/xgb_binary_UNSWNB15.pkl"
results_path = "/content/drive/MyDrive/UNSW_NB15/xgb_binary_results.json"

# -------------------
# 💾 Save model
# -------------------
joblib.dump(xgb_model, model_path)

# -------------------
# 💾 Save results to JSON
# -------------------
results_dict = {
    "model": "XGBoost Binary UNSW-NB15",
    "accuracy": round(acc, 4),
    "weighted_f1": round(f1, 4),
    "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
}

with open(results_path, "w") as f:
    json.dump(results_dict, f, indent=4)

print(f"\n💾 Model saved to: {model_path}")
print(f"💾 Results saved to: {results_path}")

!pip install catboost

# ===============================================================
# 🐱 CATBOOST — Binary Classification for UNSW-NB15
# ===============================================================

import time, json, joblib
import pandas as pd
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, f1_score, classification_report

# ---------------------------------------------------------------
# ✅ Train CatBoost Binary Model
# ---------------------------------------------------------------
print("\n🚀 Training CatBoost Binary Model...")
start = time.time()

cat_model = CatBoostClassifier(
    iterations=500,
    learning_rate=0.05,
    depth=8,
    loss_function='Logloss',
    eval_metric='Accuracy',
    verbose=100,
    random_seed=42
)

cat_model.fit(X_train_res, y_train_res, eval_set=(X_test, y_test), use_best_model=True)
end = time.time()

# ---------------------------------------------------------------
# 🎯 Evaluate
# ---------------------------------------------------------------
y_pred = cat_model.predict(X_test)

acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

print(f"\n✅ CatBoost Binary Accuracy: {acc:.4f}, Weighted F1: {f1:.4f}, Time: {end - start:.2f}s")
print("\n📋 Classification Report:\n", classification_report(y_test, y_pred))

# ---------------------------------------------------------------
# 💾 Save Model and Results
# ---------------------------------------------------------------
model_path = "/content/drive/MyDrive/UNSW_NB15/catboost_binary_UNSWNB15.pkl"
results_path = "/content/drive/MyDrive/UNSW_NB15/catboost_binary_results.json"

# Save model
joblib.dump(cat_model, model_path)

# Save results
results_dict = {
    "model": "CatBoost Binary UNSW-NB15",
    "accuracy": round(acc, 4),
    "weighted_f1": round(f1, 4),
    "train_time_sec": round(end - start, 2),
    "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
}

with open(results_path, "w") as f:
    json.dump(results_dict, f, indent=4)

print(f"\n💾 Model saved to: {model_path}")
print(f"💾 Results saved to: {results_path}")