# -*- coding: utf-8 -*-
"""Copy of CIC_17final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8_sGzU73vJfNedzVYPTHFiJJVxpY5RN
"""

# ==========================
# STEP 1: Import Libraries
# ==========================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

import warnings
warnings.filterwarnings('ignore')

# =========================================
# STEP 2: MOUNT GOOGLE DRIVE AND LOAD PARQUET DATA
# =========================================
from google.colab import drive
import os
import pandas as pd

drive.mount('/content/drive')

# Path to your dataset folder
data_path = '/content/drive/MyDrive/CIC_17/'

# List all files inside the folder
files = os.listdir(data_path)
print("📁 Files in dataset folder:", files)

# Load all Parquet files
df_list = []
for f in files:
    if f.endswith('.parquet'):
        file_path = os.path.join(data_path, f)
        print("📄 Loading:", f)
        temp_df = pd.read_parquet(file_path)
        df_list.append(temp_df)

# Combine all Parquet datasets
if len(df_list) > 0:
    df = pd.concat(df_list, ignore_index=True)
    print("✅ Dataset loaded successfully.")
    print("Shape:", df.shape)
    print("\n🔍 Columns:", df.columns[:10], "...")
else:
    raise ValueError("⚠️ No Parquet files found or loaded. Check your folder path or file format.")

# =============================
# ⚙️ Step 0: Subsample Dataset
# =============================

import numpy as np
import pandas as pd

# Suppose your combined DataFrame is named `df`
print("Original shape:", df.shape)

# Use only 10% (or 20%) of the total data
SAMPLE_FRACTION = 0.1   # use 0.2 for 20%
df_sampled = df.sample(frac=SAMPLE_FRACTION, random_state=42)

print(f"✅ Using {SAMPLE_FRACTION*100:.0f}% sample of dataset")
print("Sampled shape:", df_sampled.shape)

# Replace your working dataframe
df = df_sampled.copy()

# =========================================
# STEP 1 — Data Preprocessing (Z-score)
# =========================================
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

print("\n🧹 Starting preprocessing...")

# Detect label column automatically
label_cols = [c for c in df.columns if c.lower() in ['label', 'labels', 'attack', 'attack type']]
if not label_cols:
    raise Exception("⚠️ No label column found! Check dataset column names.")
label_col = label_cols[0]
print(f"🎯 Using '{label_col}' as label column")

# Drop unneeded columns
drop_cols = [c for c in df.columns if any(x in c.lower() for x in ['flow id', 'timestamp', 'source', 'destination'])]
df.drop(columns=drop_cols, inplace=True, errors='ignore')

# Clean missing/infinite values
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

# Encode categorical columns
cat_cols = df.select_dtypes(include='object').columns.tolist()
print(f"📦 Encoding categorical columns: {cat_cols}")

le = LabelEncoder()
for col in cat_cols:
    df[col] = le.fit_transform(df[col])

# Encode label column separately
df[label_col] = LabelEncoder().fit_transform(df[label_col])

# Separate features and labels
X = df.drop(label_col, axis=1)
y = df[label_col]

# Z-score normalization
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("\n✅ Preprocessing Complete!")
print(f"Feature matrix shape: {X_scaled.shape}")
print(f"Target vector shape: {y.shape}")
print(f"Unique label classes: {np.unique(y)}")

# ===============================================================
# STEP 2 — HYBRID FEATURE SELECTION (OPTIMIZED GA)
# ===============================================================
# ===============================================================
# STEP 2 — HYBRID FEATURE SELECTION (OPTIMIZED GA)
# ===============================================================
import numpy as np
import pandas as pd
import time, gc, joblib, random, os, warnings
from sklearn.feature_selection import mutual_info_classif
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
warnings.filterwarnings('ignore')

RANDOM_STATE = 42
SUBSAMPLE = 80000           # faster but still representative
FILTER_TOP = 40
POP_SIZE = 12
N_GEN = 12
MUT_RATE = 0.15
KNN_FIT_K = 5
KNN_FIT_CV = 2
TOP_FINAL = 20
SAVE_PATH = "/content/drive/MyDrive/CIC_17"

print("Preparing optimized GA data...")

# ✅ Convert X_scaled back to DataFrame if it’s a NumPy array
if isinstance(X_scaled, np.ndarray):
    X_df = pd.DataFrame(X_scaled, columns=[f"f{i}" for i in range(X_scaled.shape[1])])
else:
    X_df = X_scaled.copy()

y_arr = np.array(y)
feature_names = list(X_df.columns)




# --- Subsample ---
rng = np.random.default_rng(RANDOM_STATE)
sel_idx = rng.choice(X_df.shape[0], size=min(SUBSAMPLE, X_df.shape[0]), replace=False)
X_sub_df = X_df.iloc[sel_idx].reset_index(drop=True)
y_sub = y_arr[sel_idx]
X_sub = X_sub_df.values.astype(np.float32)
print(f"Subsampled shape for GA: {X_sub.shape}")

# --- Filter stage ---
print("\n[1] Filter: mutual information (top {})".format(FILTER_TOP))
mi = mutual_info_classif(X_sub, y_sub, random_state=RANDOM_STATE)
mi_series = pd.Series(mi, index=feature_names)
selected_filter = mi_series.sort_values(ascending=False).head(FILTER_TOP).index.tolist()
print(f"Top-{FILTER_TOP} features:\n{selected_filter}\n")
X_filt = X_sub[:, [feature_names.index(f) for f in selected_filter]].astype(np.float32)

# --- GA stage ---
print("[2] GA Stage (optimized) — may take 15–25 min total...")
random.seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)

def knn_fitness_mask(mask):
    cols = [i for i, b in enumerate(mask) if b]
    if not cols:
        return 0.0
    Xtmp = X_filt[:, cols]
    knn = KNeighborsClassifier(n_neighbors=KNN_FIT_K)
    try:
        return float(cross_val_score(knn, Xtmp, y_sub, cv=KNN_FIT_CV, scoring='accuracy', n_jobs=2).mean())
    except Exception:
        return 0.0

n_feat = len(selected_filter)
pop = [np.random.randint(0,2,n_feat).astype(np.int8) for _ in range(POP_SIZE)]
best_mask, best_score = None, -1

for g in range(1, N_GEN+1):
    fitness = np.array([knn_fitness_mask(ind) for ind in pop], dtype=np.float32)
    gen_best = fitness.max(); gen_mean = fitness.mean()
    if gen_best > best_score:
        best_score = gen_best
        best_mask = pop[int(np.argmax(fitness))].copy()
    print(f"Gen {g}/{N_GEN}: best={gen_best:.4f} mean={gen_mean:.4f}")

    total = fitness.sum() or 1.0
    probs = (fitness / total)
    probs = probs / probs.sum()
    new_pop = []
    for _ in range(POP_SIZE//2):
        parents = np.random.choice(range(POP_SIZE), 2, p=probs)
        p1, p2 = pop[parents[0]], pop[parents[1]]
        cx = np.random.randint(1, n_feat-1)
        c1 = np.concatenate([p1[:cx], p2[cx:]])
        c2 = np.concatenate([p2[:cx], p1[cx:]])
        for c in (c1, c2):
            r = np.random.random(size=c.shape)
            c[r<MUT_RATE] = 1 - c[r<MUT_RATE]
            new_pop.append(c.astype(np.int8))
    pop = new_pop
    gc.collect()

print(f"\n✅ GA done. Best score={best_score:.4f}")
sbm_selected = [selected_filter[i] for i,b in enumerate(best_mask) if b==1]
print(f"SBM-selected {len(sbm_selected)} features:\n{sbm_selected}")

# --- RFR ranking ---
print("\n[3] RandomForest ranking on SBM features...")
X_rfr = X_sub_df[sbm_selected].values.astype(np.float32)
rfr = RandomForestClassifier(n_estimators=200, random_state=RANDOM_STATE, n_jobs=2)
rfr.fit(X_rfr, y_sub)
imp = pd.Series(rfr.feature_importances_, index=sbm_selected).sort_values(ascending=False)
final_features = imp.head(TOP_FINAL).index.tolist()
print(f"\n🔥 Final {TOP_FINAL} hybrid-selected features:\n{final_features}")

# --- Save ---
import joblib, os
joblib.dump(final_features, os.path.join(SAVE_PATH, "final_hybrid_features_OPTGA.pkl"))
print("\n💾 Saved optimized GA feature list to Drive.")

# =========================================
# STEP 3 — SMOTE Balancing (Optimized & Stable)
# =========================================
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
import joblib, os

# --- Paths ---
SAVE_PATH = "/content/drive/MyDrive/CIC_17"

# --- Load preprocessed dataset ---
df = pd.read_csv(os.path.join(SAVE_PATH, "preprocessed_cic17.csv"))
print("Loaded preprocessed data:", df.shape)

# --- Load optimized GA-selected feature list ---
final_features = joblib.load(os.path.join(SAVE_PATH, "final_hybrid_features_OPTGA.pkl"))
print("Using optimized GA hybrid features:", final_features)

# --- Map fXX feature names to actual column names ---
feature_map = {f"f{i}": col for i, col in enumerate(df.columns[:-1], start=1)}
mapped_features = [feature_map[f] for f in final_features if f in feature_map]

print(f"Mapped feature columns found: {len(mapped_features)}")
print("Example mapping:", mapped_features[:5])

# --- Define label column ---
label_col = "Label"

# --- Split into features (X) and target (y) ---
X = df[mapped_features]
y = df[label_col]

# --- Train-test split (stratified for balance) ---
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, stratify=y, random_state=42
)
print(f"\nTrain: {X_train.shape},  Test: {X_test.shape}")
print("Before SMOTE class distribution:\n", y_train.value_counts().to_dict())

# --- Optional: Work with smaller subset for faster testing (comment if not needed) ---
# X_train = X_train.sample(frac=0.2, random_state=42)
# y_train = y_train.loc[X_train.index]
# print(f"\nUsing subset for SMOTE: {X_train.shape}")

# --- Apply SMOTE ---
print("\n🌀 Applying SMOTE oversampling (this may take 2–5 min)...")
sm = SMOTE(random_state=42, sampling_strategy='auto', k_neighbors=3)
X_res, y_res = sm.fit_resample(X_train, y_train)

# --- Results ---
print("\n✅ After SMOTE:")
print("Resampled shape:", X_res.shape)
print("Class distribution after SMOTE:\n", pd.Series(y_res).value_counts().to_dict())

# --- Save processed balanced data ---
np.savez_compressed(os.path.join(SAVE_PATH, "smote_train_small.npz"),
                    X_train=X_res, y_train=y_res)
np.savez_compressed(os.path.join(SAVE_PATH, "smote_test_small.npz"),
                    X_test=X_test, y_test=y_test)

print("\n💾 Saved balanced data to Drive:")
print(" - smote_train_small.npz")
print(" - smote_test_small.npz")

import numpy as np

# Path where your SMOTE-balanced data is saved
SAVE_PATH = "/content/drive/MyDrive/CIC_17"

# Load SMOTE-balanced data
data = np.load(f"{SAVE_PATH}/smote_train_small.npz", allow_pickle=True)
X_res, y_res = data["X_train"], data["y_train"]

# 🧠 Sample only 10% of SMOTE data to save RAM
rng = np.random.default_rng(42)
subset_idx = rng.choice(X_res.shape[0], size=int(0.1 * X_res.shape[0]), replace=False)
X_res, y_res = X_res[subset_idx], y_res[subset_idx]

print("✅ Subsampled SMOTE data:", X_res.shape, y_res.shape)

# Save this lighter version (optional)
np.savez_compressed(f"{SAVE_PATH}/smote_train_10pct.npz",
                    X_train=X_res, y_train=y_res)

print(f"💾 Saved 10% subset to: {SAVE_PATH}/smote_train_10pct.npz")

# --- 1️⃣ Load the subsampled SMOTE data ---
import numpy as np, joblib, os
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

SAVE_PATH = "/content/drive/MyDrive/CIC_17"

data = np.load(f"{SAVE_PATH}/smote_train_10pct.npz", allow_pickle=True)
X_train_full, y_train_full = data["X_train"], data["y_train"]

# --- 2️⃣ Split for local validation ---
X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full,
                                                  test_size=0.2, random_state=42, stratify=y_train_full)

print(f"Training shape: {X_train.shape}, Validation shape: {X_val.shape}")

# --- 3️⃣ Train Random Forest (tuned for speed) ---
rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=25,
    min_samples_split=10,
    n_jobs=-1,
    random_state=42,
    class_weight='balanced_subsample'
)
rf.fit(X_train, y_train)

# --- 4️⃣ Evaluate ---
y_pred = rf.predict(X_val)

print("\n✅ Random Forest Results:")
print("Accuracy:", accuracy_score(y_val, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_val, y_pred))
print("\nClassification Report:\n", classification_report(y_val, y_pred))

# --- 5️⃣ Save trained model ---
joblib.dump(rf, os.path.join(SAVE_PATH, "RF_trained_10pct.pkl"))
print(f"💾 Model saved to: {SAVE_PATH}/RF_trained_10pct.pkl")

# =========================================
# STEP — LightGBM on 10% SMOTE data
# =========================================
import numpy as np
import pandas as pd
import lightgbm as lgb
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
import joblib, os
import matplotlib.pyplot as plt

# --- Paths ---
SAVE_PATH = "/content/drive/MyDrive/CIC_17"

# --- Load balanced subset ---
data = np.load(os.path.join(SAVE_PATH, "smote_train_10pct.npz"))
X, y = data["X_train"], data["y_train"]

print(f"✅ Loaded 10% SMOTE subset: {X.shape}, {y.shape}")

# --- Split into train/test ---
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)
print(f"Train: {X_train.shape}, Test: {X_test.shape}")

# --- Define LightGBM model ---
lgbm = lgb.LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=12,
    num_leaves=64,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

# --- Train ---
print("\n🚀 Training LightGBM...")
lgbm.fit(X_train, y_train)

# --- Predict ---
y_pred = lgbm.predict(X_test)

# --- Evaluate ---
print("\n📊 Classification Report:")
print(classification_report(y_test, y_pred, digits=4))

acc = accuracy_score(y_test, y_pred)
print(f"✅ Accuracy: {acc:.4f}")

# --- Confusion Matrix ---
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", cm)

# --- Feature Importance ---
plt.figure(figsize=(10,6))
lgb.plot_importance(lgbm, max_num_features=15, importance_type='gain', title='Top 15 Feature Importances')
plt.tight_layout()
plt.show()

# --- Save Model ---
joblib.dump(lgbm, os.path.join(SAVE_PATH, "lightgbm_ids_model.pkl"))
print("\n💾 Saved LightGBM model to Drive: lightgbm_ids_model.pkl")

# =========================================
# STEP — XGBoost on 10% SMOTE data
# =========================================
import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import joblib, os

# --- Paths ---
SAVE_PATH = "/content/drive/MyDrive/CIC_17"

# --- Load 10% SMOTE subset ---
data = np.load(os.path.join(SAVE_PATH, "smote_train_10pct.npz"))
X, y = data["X_train"], data["y_train"]

print(f"✅ Loaded 10% SMOTE subset: {X.shape}, {y.shape}")

# --- Split into train/test ---
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)
print(f"Train: {X_train.shape}, Test: {X_test.shape}")

# --- Define XGBoost model ---
xgb_model = xgb.XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=12,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='multi:softmax',  # for multiclass classification
    num_class=len(np.unique(y)),  # auto-detect classes
    eval_metric='mlogloss',
    random_state=42,
    n_jobs=-1
)

# --- Train ---
print("\n🚀 Training XGBoost...")
xgb_model.fit(X_train, y_train)

# --- Predict ---
y_pred = xgb_model.predict(X_test)

# --- Evaluate ---
print("\n📊 Classification Report:")
print(classification_report(y_test, y_pred, digits=4))

acc = accuracy_score(y_test, y_pred)
print(f"✅ Accuracy: {acc:.4f}")

# --- Confusion Matrix ---
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", cm)

# --- Feature Importance Plot ---
plt.figure(figsize=(10,6))
xgb.plot_importance(xgb_model, max_num_features=15, importance_type='gain', title='Top 15 XGBoost Feature Importances')
plt.tight_layout()
plt.show()

# --- Save Model ---
joblib.dump(xgb_model, os.path.join(SAVE_PATH, "xgboost_ids_model.pkl"))
print("\n💾 Saved XGBoost model to Drive: xgboost_ids_model.pkl")

print(os.listdir("/content/drive/MyDrive/CIC_17"))

import os

BASE_PATH = "/content/drive/MyDrive/CIC_17"
print("📂 Files in CIC_17 folder:\n")
for f in os.listdir(BASE_PATH):
    print(f)

import numpy as np
import joblib, os
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# --- Base path where models and data are stored ---
BASE_PATH = "/content/drive/MyDrive/CIC_17"

# --- Load your saved models ---
rf_model = joblib.load(os.path.join(BASE_PATH, "RF_trained_10pct.pkl"))
lgb_model = joblib.load(os.path.join(BASE_PATH, "lightgbm_ids_model.pkl"))
xgb_model = joblib.load(os.path.join(BASE_PATH, "xgboost_ids_model.pkl"))
print("✅ Models loaded successfully!")

# --- Load 10% SMOTE subset ---
data = np.load(os.path.join(BASE_PATH, "smote_train_10pct.npz"))
X = data["X_train"]
y = data["y_train"]
print("✅ Loaded dataset:", X.shape, y.shape)

# --- Split for evaluation (keep 20% for test) ---
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# --- Create soft voting ensemble ---
ensemble = VotingClassifier(
    estimators=[
        ('rf', rf_model),
        ('lgb', lgb_model),
        ('xgb', xgb_model)
    ],
    voting='soft',
    n_jobs=-1
)

# --- Train ensemble ---
print("\n🚀 Training Ensemble...")
ensemble.fit(X_train, y_train)

# --- Evaluate ensemble ---
y_pred = ensemble.predict(X_test)

print("\n📊 Classification Report:\n")
print(classification_report(y_test, y_pred))
print("✅ Accuracy:", accuracy_score(y_test, y_pred))

# --- Confusion matrix ---
cm = confusion_matrix(y_test, y_pred)

# 🔹 PRINT NUMERIC VALUES
print("\n📌 Confusion Matrix Values:")
print(cm)

# --- Plot confusion matrix ---
plt.figure(figsize=(10, 6))
sns.heatmap(cm, cmap='Blues', annot=True, fmt='d')  # annot=True shows values
plt.title("Confusion Matrix - Ensemble")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

# --- Save ensemble model ---
ensemble_path = os.path.join(BASE_PATH, "ensemble_voting_model.pkl")
joblib.dump(ensemble, ensemble_path)
print(f"\n💾 Ensemble model saved to: {ensemble_path}")

!pip install catboost -q

# ===============================================================
# 🐱 CATBOOST MODEL FOR CIC_17
# ===============================================================
from catboost import CatBoostClassifier
import joblib
import os
from sklearn.metrics import classification_report, accuracy_score

# ✅ Load preprocessed data (X_train, X_test, y_train, y_test)
# You already have these from your previous CIC_17 workflow
# Just make sure variables are in memory, or reload from saved .npz if needed:
# data = np.load('/content/drive/MyDrive/CIC_17/smote_train_10pct.npz')
# X_train, X_test, y_train, y_test = data['X_train'], data['X_test'], data['y_train'], data['y_test']

print(f"✅ Loaded dataset: {X_train.shape} {y_train.shape}")

# ===============================================================
# Load final hybrid-selected features if available
# ===============================================================
feature_path = "/content/drive/MyDrive/CIC_17/final_hybrid_features_OPTGA.pkl"
if os.path.exists(feature_path):
    selected_features = joblib.load(feature_path)
    print(f"✅ Loaded {len(selected_features)} hybrid-selected features.")
    # Keep only selected features
    X_train = pd.DataFrame(X_train, columns=selected_features)
    X_test = pd.DataFrame(X_test, columns=selected_features)
else:
    print("⚠️ No hybrid feature list found — training on all features.")

# ===============================================================
# Initialize and Train CatBoost
# ===============================================================
cat_model = CatBoostClassifier(
    iterations=500,             # more → better accuracy
    learning_rate=0.05,
    depth=8,
    loss_function='MultiClass',
    eval_metric='Accuracy',
    random_seed=42,
    verbose=100,                # prints progress every 100 iterations
    task_type="CPU"             # can set to "GPU" if Colab GPU is enabled
)

print("🚀 Training CatBoost model...")
cat_model.fit(X_train, y_train, eval_set=(X_test, y_test), use_best_model=True)

# ===============================================================
# Evaluate the Model
# ===============================================================
y_pred = cat_model.predict(X_test)
y_pred = y_pred.flatten()  # reshape if needed

print("\n📊 Classification Report:")
print(classification_report(y_test, y_pred))
acc = accuracy_score(y_test, y_pred)
print(f"✅ Accuracy: {acc:.4f}")

# ===============================================================
# Save Model
# ===============================================================
save_path = "/content/drive/MyDrive/CIC_17/catboost_ids_model.cbm"
cat_model.save_model(save_path)
print(f"\n💾 CatBoost model saved to: {save_path}")