# -*- coding: utf-8 -*-
"""Binary_CIC_18final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RVpgyb1sEoYxGf6aF8revzQ22Ym-XtZe
"""

# STEP 1: Import Libraries
# ==========================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import os

dataset_path = "/content/drive/MyDrive/archive (11)/CSE-CIC-IDS2018"

# List files
files = os.listdir(dataset_path)
print("Files in folder:", files)

# Load ONE CSV to test (example: Bot.csv)
df = pd.read_csv(f"{dataset_path}/Bot.csv")

df.head()

import pandas as pd
import os

dataset_path = "/content/drive/MyDrive/archive (11)/CSE-CIC-IDS2018"
output_file = "/content/drive/MyDrive/CICIDS2018_merged.csv"

# get all csv filenames
csv_files = [f for f in os.listdir(dataset_path) if f.endswith('.csv')]

print("Found files:", csv_files)

# Create empty file first
open(output_file, "w").close()

first_file = True

# Read each file in chunks
for file in csv_files:
    print(f"\n📌 Processing: {file}")
    file_path = f"{dataset_path}/{file}"

    # Read in chunks
    for chunk in pd.read_csv(file_path, chunksize=50000, low_memory=False):

        # Write header only for 1st file
        chunk.to_csv(output_file, mode='a', index=False, header=first_file)
        first_file = False

print("\n✅ DONE! Merged CSV saved at:")
print(output_file)

import pandas as pd
from sklearn.model_selection import train_test_split

merged_path = "/content/drive/MyDrive/CICIDS2018_merged.csv"

chunk_size = 100000     # read 1 lakh rows at a time
sample_fraction = 0.05   # sample 5% from each chunk (change to 0.02 if RAM low)

samples = []  # store sampled chunks

for chunk in pd.read_csv(merged_path, chunksize=chunk_size, low_memory=False):

    # Create binary label
    chunk['label'] = chunk['Label'].apply(
        lambda x: 0 if x.lower() == 'benign' else 1
    )

    # Stratified sample per chunk
    try:
        X = chunk.drop(columns=['Label', 'label'])
        y = chunk['label']

        X_s, _, y_s, _ = train_test_split(
            X, y,
            train_size=sample_fraction,
            stratify=y,
            random_state=42
        )

        temp = X_s.copy()
        temp['label'] = y_s

        samples.append(temp)

    except:
        continue  # skip very small chunks

# Combine all sampled mini-chunks
df_small = pd.concat(samples, ignore_index=True)

print("Final Sampled Shape:", df_small.shape)
print(df_small['label'].value_counts())

df_small.to_csv("/content/drive/MyDrive/CICIDS2018_small.csv", index=False)

print("Saved:", "/content/drive/MyDrive/CICIDS2018_small.csv")

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/CICIDS2018_small.csv")
print(df.shape)

import numpy as np

df = df.replace([np.inf, -np.inf], np.nan)
df = df.dropna()

X = df.drop(columns=['label'])
y = df['label']

X = X.select_dtypes(include='number')
print("Numeric features:", X.shape[1])

from sklearn.feature_selection import mutual_info_classif

mi_scores = mutual_info_classif(X, y, random_state=42)
mi_series = pd.Series(mi_scores, index=X.columns).sort_values(ascending=False)

top_k = 40
mi_features = mi_series.head(top_k).index.tolist()

X_mi = X[mi_features]

print("Selected by MI:", len(mi_features))
mi_features

# ========== STEP 1: Prepare data for GA (train / val split) ==========
import pandas as pd
from sklearn.model_selection import train_test_split
from collections import Counter

# Load sampled file (only if not already in memory)
# df = pd.read_csv("/content/drive/MyDrive/CICIDS2018_small.csv")

# If df already exists in memory use it; otherwise uncomment previous line.

# MI-selected features you provided (use exactly these names)
mi_features = [
 'Init Fwd Win Byts','Dst Port','Fwd Header Len','Fwd Pkt Len Mean','Fwd Seg Size Avg',
 'Subflow Fwd Byts','TotLen Fwd Pkts','Fwd Pkt Len Max','Bwd Pkt Len Mean','Bwd Seg Size Avg',
 'TotLen Bwd Pkts','Subflow Bwd Byts','Bwd Pkt Len Max','Pkt Len Mean','Pkt Len Var',
 'Pkt Len Std','Pkt Len Max','Fwd Pkts/s','Pkt Size Avg','Flow IAT Max',
 'Flow IAT Mean','Fwd IAT Mean','Fwd IAT Max','Flow Duration','Fwd IAT Tot',
 'Bwd Pkts/s','Fwd Pkt Len Std','Flow IAT Min','Bwd Pkt Len Std','Bwd Header Len',
 'Fwd IAT Min','Init Bwd Win Byts','Flow Pkts/s','Flow Byts/s','Fwd Seg Size Min',
 'Tot Bwd Pkts','Subflow Bwd Pkts','Flow IAT Std','Fwd IAT Std','Subflow Fwd Pkts'
]

# sanity: check all features exist in df
missing = [c for c in mi_features if c not in df.columns]
if missing:
    raise KeyError(f"The following MI features are missing from df.columns: {missing}")

# Build X_mi and y
X_mi = df[mi_features].copy()
y = df['label'].copy()

print("Full X_mi shape:", X_mi.shape)
print("Full label distribution:", Counter(y))

# Stratified split for GA evaluation (GA will train on X_train and evaluate on X_val)
X_train_ga, X_val_ga, y_train_ga, y_val_ga = train_test_split(
    X_mi, y, test_size=0.30, stratify=y, random_state=42
)

print("\nAfter split:")
print("X_train_ga:", X_train_ga.shape, "y_train dist:", Counter(y_train_ga))
print("X_val_ga  :", X_val_ga.shape, "y_val   dist:", Counter(y_val_ga))

# Quick numeric check (no NaN / inf)
import numpy as np
if X_train_ga.isnull().any().any() or X_val_ga.isnull().any().any():
    print("\n⚠️ Warning: NaNs found in X_train_ga/X_val_ga. Consider dropping/filling them before GA.")
if np.isinf(X_train_ga.values).any() or np.isinf(X_val_ga.values).any():
    print("\n⚠️ Warning: Infs found in X_train_ga/X_val_ga. Consider replacing them before GA.")

# Save these to reuse in next steps (optional)
# X_train_ga.to_pickle("/content/X_train_ga.pkl")
# X_val_ga.to_pickle("/content/X_val_ga.pkl")
# y_train_ga.to_pickle("/content/y_train_ga.pkl")
# y_val_ga.to_pickle("/content/y_val_ga.pkl")

print("\nSTEP 1 complete. If shapes & distributions look OK I'll give the GA (LightGBM) code next.")

!pip install lightgbm deap

import numpy as np
import random
from collections import Counter
from deap import base, creator, tools
import lightgbm as lgb
from sklearn.metrics import f1_score

RANDOM_STATE = 42
random.seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)

# ===============================
# GA PARAMETERS
# ===============================
N_FEATURES = X_train_ga.shape[1]   # 40
POP_SIZE = 20
N_GEN = 10
CX_PB = 0.7
MUT_PB = 0.2

# ===============================
# GA FITNESS FUNCTION
# ===============================
def evaluate(individual):
    idx = [i for i, bit in enumerate(individual) if bit == 1]
    if len(idx) == 0:
        return (0,)

    X_tr = X_train_ga.iloc[:, idx]
    X_val = X_val_ga.iloc[:, idx]

    model = lgb.LGBMClassifier(
        objective="binary",
        n_estimators=150,
        learning_rate=0.07,
        num_leaves=31,
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )

    model.fit(X_tr, y_train_ga)
    preds = model.predict(X_val)

    score = f1_score(y_val_ga, preds)
    return (score,)


# ===============================
# CREATE INDIVIDUAL + POPULATION
# ===============================
creator.create("FitnessMax", base.Fitness, weights=(1.0,))
creator.create("Individual", list, fitness=creator.FitnessMax)

toolbox = base.Toolbox()
toolbox.register("attr_bool", lambda: random.randint(0, 1))
toolbox.register("individual", tools.initRepeat, creator.Individual,
                 toolbox.attr_bool, N_FEATURES)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

# Operators
toolbox.register("evaluate", evaluate)
toolbox.register("mate", tools.cxTwoPoint)
toolbox.register("mutate", tools.mutFlipBit, indpb=0.05)
toolbox.register("select", tools.selTournament, tournsize=3)

# ===============================
# RUN GA
# ===============================
pop = toolbox.population(n=POP_SIZE)
best_ind = None

for gen in range(N_GEN):
    print(f"\n📌 Generation {gen+1}/{N_GEN}")

    # Evaluate fitness
    fitnesses = list(map(toolbox.evaluate, pop))
    for ind, fit in zip(pop, fitnesses):
        ind.fitness.values = fit

    # Best of this generation
    gen_best = tools.selBest(pop, 1)[0]

    # Save global best
    if best_ind is None or gen_best.fitness.values[0] > best_ind.fitness.values[0]:
        best_ind = creator.Individual(gen_best)
        best_ind.fitness.values = gen_best.fitness.values

    print("Best F1 this gen:", gen_best.fitness.values[0])
    print("Best overall F1:", best_ind.fitness.values[0])

    # Create next generation
    offspring = toolbox.select(pop, len(pop))
    offspring = list(map(toolbox.clone, offspring))

    # Crossover
    for child1, child2 in zip(offspring[::2], offspring[1::2]):
        if random.random() < CX_PB:
            toolbox.mate(child1, child2)
            del child1.fitness.values
            del child2.fitness.values

    # Mutation
    for mutant in offspring:
        if random.random() < MUT_PB:
            toolbox.mutate(mutant)
            del mutant.fitness.values

    pop = offspring

# ===============================
# FINAL SELECTED FEATURES
# ===============================
best_features = [i for i, bit in enumerate(best_ind) if bit == 1]

print("\n🎉 FINAL BEST F1:", best_ind.fitness.values[0])
print("🎉 BEST FEATURE INDICES:", best_features)
print("COUNT:", len(best_features))

selected_feature_names = X_train_ga.columns[best_features]
print("\n🎯 SELECTED FEATURES:")
print(list(selected_feature_names))

from imblearn.over_sampling import SMOTE
from collections import Counter

# GA-selected feature names
selected_features = list(selected_feature_names)   # from your GA output

# Extract selected columns
X_train_fs = X_train_ga[selected_features]
X_val_fs   = X_val_ga[selected_features]

print("Before SMOTE:", Counter(y_train_ga))

# Apply SMOTE
sm = SMOTE(random_state=42, k_neighbors=5)
X_train_sm, y_train_sm = sm.fit_resample(X_train_fs, y_train_ga)

print("After SMOTE:", Counter(y_train_sm))
print("\nX_train_sm shape:", X_train_sm.shape)
print("X_val_fs shape:", X_val_fs.shape)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

rf_model2 = RandomForestClassifier(
    n_estimators=700,
    max_depth=35,
    min_samples_split=4,
    min_samples_leaf=2,
    max_features="sqrt",
    class_weight={0:1, 1:2},   # strong boost to recall for class 1
    random_state=42,
    n_jobs=-1
)

rf_model2.fit(X_train_sm, y_train_sm)
rf_preds2 = rf_model2.predict(X_val_fs)

print("Improved RF Accuracy:", accuracy_score(y_val_ga, rf_preds2))
print("\nImproved RF Classification Report:\n",
      classification_report(y_val_ga, rf_preds2))

import lightgbm as lgb
from sklearn.metrics import classification_report, accuracy_score

lgbm_high_recall = lgb.LGBMClassifier(
    objective="binary",
    boosting_type="gbdt",
    n_estimators=700,          # more trees
    learning_rate=0.025,       # smaller LR
    num_leaves=70,
    max_depth=-1,
    subsample=0.9,
    colsample_bytree=0.9,
    reg_alpha=1.5,
    reg_lambda=2.5,
    min_child_samples=20,
    class_weight={0:1, 1:3},   # bump attack class weight
    random_state=42,
    n_jobs=-1
)

lgbm_high_recall.fit(X_train_sm, y_train_sm)
preds = lgbm_high_recall.predict(X_val_fs)

print("High Recall LightGBM Accuracy:", accuracy_score(y_val_ga, preds))
print("\nClassification Report:\n", classification_report(y_val_ga, preds))

from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report

# ==============================
# Train XGBoost
# ==============================
xgb_model = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=7,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.1,
    reg_lambda=1,
    reg_alpha=0,
    objective="binary:logistic",
    random_state=42,
    n_jobs=-1,
    eval_metric="logloss"
)

xgb_model.fit(X_train_sm, y_train_sm)

# ==============================
# Predict
# ==============================
xgb_preds = xgb_model.predict(X_val_fs)

# ==============================
# Evaluate
# ==============================
print("XGBoost Accuracy:", accuracy_score(y_val_ga, xgb_preds))
print("\nClassification Report:\n", classification_report(y_val_ga, xgb_preds))

!pip install catboost

# FIXED: Use proper pandas column selection
X_fs = X[selected_features]      # selected_features = list of column names
y_fs = y

from sklearn.model_selection import train_test_split

X_train_fs, X_val_fs, y_train_fs, y_val_fs = train_test_split(
    X_fs, y_fs, test_size=0.2, random_state=42, stratify=y_fs
)

from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, classification_report

cat_model = CatBoostClassifier(
    iterations=500,
    learning_rate=0.05,
    depth=8,
    loss_function='Logloss',
    eval_metric='Accuracy',
    random_seed=42,
    verbose=100
)

cat_model.fit(X_train_fs, y_train_fs)

cat_preds = cat_model.predict(X_val_fs)

print("\nCatBoost Accuracy:", accuracy_score(y_val_fs, cat_preds))
print("\nClassification Report:\n", classification_report(y_val_fs, cat_preds))