# -*- coding: utf-8 -*-
"""Copy of UNSW_NB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mjzgfA71zctY58pvyipTgSwtcEgR49q9
"""

# ==========================
# STEP 1: Import Libraries
# ==========================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

import warnings
warnings.filterwarnings('ignore')

# =========================================
# STEP 2: MOUNT GOOGLE DRIVE AND LOAD UNSW-NB15 DATA
# =========================================
from google.colab import drive
import os
import pandas as pd

# Mount Google Drive
drive.mount('/content/drive')

# Path to your dataset folder
data_path = '/content/drive/MyDrive/UNSW_NB/'

# List all files inside the folder
files = os.listdir(data_path)
print("📁 Files in dataset folder:", files)

# The UNSW-NB15 dataset usually has multiple CSV files:
# e.g., 'UNSW_NB15_training-set.csv', 'UNSW_NB15_testing-set.csv'
train_file = [f for f in files if 'training' in f.lower()][0]
test_file = [f for f in files if 'testing' in f.lower()][0]

# Load the CSV files
print(f"📄 Loading training set: {train_file}")
train_df = pd.read_csv(os.path.join(data_path, train_file))

print(f"📄 Loading testing set: {test_file}")
test_df = pd.read_csv(os.path.join(data_path, test_file))

# Combine them (optional but often useful for feature engineering)
df = pd.concat([train_df, test_df], ignore_index=True)

print("✅ Dataset loaded successfully.")
print("Shape:", df.shape)
print("\n🔍 Columns:", df.columns[:40].tolist(), "...")
print("\n🎯 Target column samples:", df[['label', 'attack_cat']].head())

# =========================================
# STEP 3: DATA PREPROCESSING
# =========================================
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Drop 'id' as it doesn't help with prediction
df = df.drop(columns=['id'], errors='ignore')

# Check for missing values
print("🧹 Missing values per column:\n", df.isnull().sum().sort_values(ascending=False).head())

# Fill missing categorical values with mode, numeric with median
for col in df.columns:
    if df[col].dtype == 'object':
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        df[col].fillna(df[col].median(), inplace=True)

# Identify categorical columns
cat_cols = ['proto', 'service', 'state']

# Encode categorical features
le = LabelEncoder()
for col in cat_cols:
    df[col] = le.fit_transform(df[col])

# Check encoding
print("\n🔢 Encoded categorical columns:", cat_cols)
print(df[cat_cols].head())

# Define features and target
X = df.drop(columns=['label', 'attack_cat'])
y_binary = df['label']          # For binary classification (Attack vs Normal)
y_multi = df['attack_cat']      # For multiclass classification (attack type)

# Encode multiclass target
y_multi = LabelEncoder().fit_transform(y_multi)

# Normalize numeric features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("\n✅ Preprocessing complete!")
print("Feature matrix shape:", X_scaled.shape)
print("Binary target shape:", y_binary.shape)
print("Multiclass target shape:", y_multi.shape)

import os

path = "/content/drive/MyDrive/UNSW_NB/"
print("📁 Files inside UNSW_NB folder:\n")
print(os.listdir(path))

print(df[['label', 'attack_cat']].head())
print(df['attack_cat'].value_counts())

import pandas as pd

# Paths
train_path = "/content/drive/MyDrive/UNSW_NB/UNSW_NB15_training-set.csv"
test_path = "/content/drive/MyDrive/UNSW_NB/UNSW_NB15_testing-set.csv"

# Load CSVs
df_train = pd.read_csv(train_path)
df_test = pd.read_csv(test_path)

# Merge both
df = pd.concat([df_train, df_test], ignore_index=True)

print("✅ Combined UNSW-NB15 dataset loaded successfully!")
print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist()[:10], "...")

# Check which columns remain in df
print("🧾 Columns in df:", len(df.columns))
print(df.columns.tolist())

# Recreate feature columns properly
feature_cols = [col for col in df.columns if col not in ['label', 'attack_cat']]

# Check alignment
print("✅ Features count:", len(feature_cols))
print("✅ X_scaled shape:", X_scaled.shape)

# 1️⃣ Identify non-numeric columns (these should all be numeric)
non_numeric = df.drop(columns=['label', 'attack_cat']).select_dtypes(exclude=['number']).columns.tolist()
print("⚠️ Non-numeric columns found:", non_numeric)

# 2️⃣ Force convert them to numeric (0/1 or numeric values)
for col in non_numeric:
    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

# 3️⃣ Recreate features and scale again
feature_cols = [col for col in df.columns if col not in ['label', 'attack_cat']]
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df[feature_cols])

print("✅ Fixed! New X_scaled shape:", X_scaled.shape)
print("✅ Feature count:", len(feature_cols))

# =========================================
# STEP 1 — Train/Test Split + Mutual Information
# =========================================
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import mutual_info_classif

# -------------------------------------------------
# Convert scaled array back to DataFrame
# -------------------------------------------------
feature_cols = df.drop(columns=['label', 'attack_cat']).columns.tolist()
X_df = pd.DataFrame(X_scaled, columns=feature_cols)

# -------------------------------------------------
# Stratified Train-Test Split (Multiclass)
# -------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_df,
    y_multi,
    test_size=0.2,
    stratify=y_multi,
    random_state=42
)

print(f"✅ Split complete — Train: {X_train.shape}, Test: {X_test.shape}")

# -------------------------------------------------
# Identify discrete features (important for MI)
# -------------------------------------------------
discrete_features = X_train.dtypes == int

# -------------------------------------------------
# Compute Mutual Information
# -------------------------------------------------
print("🔍 Computing Mutual Information scores...")
mi_scores = mutual_info_classif(
    X_train,
    y_train,
    discrete_features=discrete_features,
    random_state=42
)

# Create MI Series
mi_ser = pd.Series(mi_scores, index=X_train.columns)
mi_ser = mi_ser.sort_values(ascending=False)

# -------------------------------------------------
# Select Top-40 Features (out of 43 total)
# -------------------------------------------------
TOP_K = 40
top_features = mi_ser.head(TOP_K).index.tolist()

print(f"\n🏆 Top {TOP_K} Features by Mutual Information:")
for i, f in enumerate(top_features, 1):
    print(f"{i:2d}. {f:25s}  MI = {mi_ser[f]:.4f}")

# -------------------------------------------------
# Reduce feature space (for GA)
# -------------------------------------------------
X_train_mi = X_train[top_features]
X_test_mi = X_test[top_features]

print(f"\n📉 Feature reduction: {X_train.shape[1]} → {X_train_mi.shape[1]}")

# -------------------------------------------------
# Save results for reproducibility
# -------------------------------------------------
mi_ser.to_csv("mi_feature_scores.csv")
pd.Series(top_features).to_csv("top_features_mi.csv", index=False)

print("\n✅ Saved:")
print("   • mi_feature_scores.csv")
print("   • top_features_mi.csv")

# =========================================
# Prepare MI-selected features for MULTICLASS
# =========================================
import pandas as pd
from sklearn.preprocessing import StandardScaler

# -------------------------------------------------
# Load MI-selected feature names
# -------------------------------------------------
mi_file = pd.read_csv("top_features_mi.csv", header=None)

# Clean feature list (remove index column & leakage-prone 'id')
top_features = [
    f for f in mi_file[0].astype(str).tolist()
    if f not in ['0', 'id']
]

print(f"✅ Cleaned top MI features: {len(top_features)}")
print(top_features)

# -------------------------------------------------
# Subset original DataFrame using selected features
# -------------------------------------------------
X_top_df = df[top_features].copy()

# -------------------------------------------------
# Scale selected features
# -------------------------------------------------
scaler = StandardScaler()
X_top = scaler.fit_transform(X_top_df)

# -------------------------------------------------
# Multiclass target
# -------------------------------------------------
y_top = y_multi.copy()

print("✅ X_top shape:", X_top.shape)
print("✅ y_top shape:", y_top.shape)

!pip install deap

import pandas as pd

# -------------------------------------------------
# Clean top MI features (remove stray index & leakage)
# -------------------------------------------------
top_features = [
    f for f in top_features
    if f not in ['0', 'id']
]

print(f"✅ Using {len(top_features)} MI-selected features")

# -------------------------------------------------
# Convert scaled NumPy array back to DataFrame
# -------------------------------------------------
feature_cols = df.drop(columns=['attack_cat', 'label']).columns.tolist()
X_df = pd.DataFrame(X_scaled, columns=feature_cols)

# -------------------------------------------------
# Subset using MI-selected feature names
# -------------------------------------------------
X_top = X_df[top_features].copy()

# -------------------------------------------------
# Multiclass target
# -------------------------------------------------
y_top = y_multi.copy()

print("✅ X_top shape:", X_top.shape)
print("✅ y_top shape:", y_top.shape)

# ==============================================
# GA + LightGBM FEATURE SELECTION (MULTICLASS)
# ==============================================

import numpy as np
import random, warnings, pickle
from tqdm import tqdm

from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from lightgbm import LGBMClassifier

from deap import base, creator, tools

warnings.filterwarnings("ignore")

# -------------------------------------------------
# INPUT:
# X_top -> DataFrame of candidate features
# y_top -> Multiclass labels (encoded)
# -------------------------------------------------

# -------------------------------------------------
# Small stratified subset for GA fitness (speed)
# -------------------------------------------------
X_ga, _, y_ga, _ = train_test_split(
    X_top,
    y_top,
    test_size=0.75,
    stratify=y_top,
    random_state=42
)

print(f"✅ GA Fitness Samples: {X_ga.shape[0]}")

# -------------------------------------------------
# GA PARAMETERS
# -------------------------------------------------
POP_SIZE = 20
N_GEN = 8
CX_PROB = 0.7
MUT_PROB = 0.3

# -------------------------------------------------
# DEAP SETUP
# -------------------------------------------------
if "FitnessMax" not in creator.__dict__:
    creator.create("FitnessMax", base.Fitness, weights=(1.0,))
if "Individual" not in creator.__dict__:
    creator.create("Individual", list, fitness=creator.FitnessMax)

toolbox = base.Toolbox()
toolbox.register("attr_bool", random.randint, 0, 1)

toolbox.register(
    "individual",
    tools.initRepeat,
    creator.Individual,
    toolbox.attr_bool,
    n=len(X_top.columns)
)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

# -------------------------------------------------
# FITNESS FUNCTION (Macro-F1)
# -------------------------------------------------
def evaluate(individual):

    selected_features = [
        col for bit, col in zip(individual, X_top.columns) if bit == 1
    ]

    if len(selected_features) < 3:
        return (0.0,)

    X_sel = X_ga[selected_features]

    X_tr, X_val, y_tr, y_val = train_test_split(
        X_sel,
        y_ga,
        test_size=0.3,
        stratify=y_ga,
        random_state=42
    )

    model = LGBMClassifier(
        objective="multiclass",
        num_class=len(np.unique(y_top)),
        n_estimators=200,
        learning_rate=0.05,
        max_depth=8,
        subsample=0.8,
        colsample_bytree=0.8,
        class_weight="balanced",
        n_jobs=-1,
        random_state=42
    )

    model.fit(X_tr, y_tr)
    y_pred = model.predict(X_val)

    score = f1_score(y_val, y_pred, average="macro")
    return (score,)

toolbox.register("evaluate", evaluate)
toolbox.register("mate", tools.cxTwoPoint)
toolbox.register("mutate", tools.mutFlipBit, indpb=0.1)
toolbox.register("select", tools.selTournament, tournsize=3)

# -------------------------------------------------
# RUN GA
# -------------------------------------------------
population = toolbox.population(n=POP_SIZE)

best_score = 0.0
best_features = []

gen_best_scores = []
gen_mean_scores = []

print(f"\n⚙️ Running GA for {N_GEN} generations...")

for gen in tqdm(range(N_GEN), desc="GA Evolution"):

    offspring = list(map(toolbox.clone,
                          toolbox.select(population, len(population))))

    for c1, c2 in zip(offspring[::2], offspring[1::2]):
        if random.random() < CX_PROB:
            toolbox.mate(c1, c2)
            del c1.fitness.values, c2.fitness.values

    for mutant in offspring:
        if random.random() < MUT_PROB:
            toolbox.mutate(mutant)
            del mutant.fitness.values

    invalid = [ind for ind in offspring if not ind.fitness.valid]
    for ind in invalid:
        ind.fitness.values = toolbox.evaluate(ind)

    population[:] = offspring

    fits = [ind.fitness.values[0] for ind in population]

    gen_best = np.max(fits)
    gen_mean = np.mean(fits)

    gen_best_scores.append(gen_best)
    gen_mean_scores.append(gen_mean)

    if gen_best > best_score:
        best_score = gen_best
        best_ind = population[np.argmax(fits)]
        best_features = [
            col for bit, col in zip(best_ind, X_top.columns) if bit == 1
        ]

    print(
        f"🧬 Gen {gen+1}/{N_GEN} | "
        f"Best Macro-F1: {gen_best:.4f} | "
        f"Mean Macro-F1: {gen_mean:.4f}"
    )

# -------------------------------------------------
# SAVE SELECTED FEATURES
# -------------------------------------------------
with open("ga_lgbm_selected_features.pkl", "wb") as f:
    pickle.dump(best_features, f)

# -------------------------------------------------
# FINAL RESULTS
# -------------------------------------------------
print("\n================ FINAL GA RESULTS ================")
print(f"🏆 Best Macro-F1 (Accuracy): {np.max(gen_best_scores):.4f}")
print(f"📈 Mean Macro-F1 (Accuracy): {np.mean(gen_mean_scores):.4f}")
print(f"📊 Selected Features: {len(best_features)}")
print(best_features)

import pandas as pd
import numpy as np
import lightgbm as lgb
import pickle, joblib
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.combine import SMOTEENN
import warnings
warnings.filterwarnings("ignore")

with open("ga_lgbm_selected_features.pkl", "rb") as f:
    best_features = pickle.load(f)

print(f"✅ Using {len(best_features)} selected features")

# Encode labels
df['attack_cat'] = df['attack_cat'].astype('category')
y = df['attack_cat'].cat.codes

# Feature matrix (already scaled)
X = pd.DataFrame(
    X_scaled,
    columns=df.drop(columns=['label', 'attack_cat']).columns
)[best_features]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

import numpy as np
import lightgbm as lgb
from imblearn.over_sampling import SMOTE
from sklearn.metrics import f1_score, classification_report

X_train_res, y_train_res = X_train, y_train

print("Original class distribution:")
print(np.bincount(y_train))

train_attack = df_train[df_train['attack_cat'] != 'Normal']
test_attack  = df_test[df_test['attack_cat'] != 'Normal']

X_train_att = train_attack.drop(['label', 'attack_cat'], axis=1).values
X_test_att  = test_attack.drop(['label', 'attack_cat'], axis=1).values

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_train_att = le.fit_transform(train_attack['attack_cat'])
y_test_att  = le.transform(test_attack['attack_cat'])

print("Attack classes:", le.classes_)

cat_cols = ['proto', 'service', 'state']

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(
    handle_unknown='ignore',
    sparse_output=False
)

X_train_cat = ohe.fit_transform(df_train[cat_cols])
X_test_cat  = ohe.transform(df_test[cat_cols])

from sklearn.metrics import f1_score

def lgb_macro_f1(preds, train_data):
    y_true = train_data.get_label()
    y_pred = np.argmax(preds.reshape(num_classes, -1), axis=0)
    return 'macro_f1', f1_score(y_true, y_pred, average='macro'), True

train_data = lgb.Dataset(X_train, label=y_train)
valid_data = lgb.Dataset(X_test, label=y_test, reference=train_data)

model = lgb.train(
    params,
    train_data,
    num_boost_round=800,
    valid_sets=[valid_data],
    feval=lgb_macro_f1,
    callbacks=[
        lgb.early_stopping(60),
        lgb.log_evaluation(50)
    ]
)

y_pred_prob = model.predict(X_test, num_iteration=model.best_iteration)
y_pred = np.argmax(y_pred_prob, axis=1)
macro_f1 = f1_score(y_test, y_pred, average='macro')

print(f"\n🏆 Final Macro-F1 Score: {macro_f1:.4f}\n")
print("Classification Report:")
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm
)

disp.plot(
    cmap='Blues',
    xticks_rotation=45
)

plt.title("Confusion Matrix – LightGBM (SMOTE)")
plt.tight_layout()
plt.show()

import pandas as pd
import joblib
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split

# ==============================================
# 1️⃣ Load GA + MI selected features
# ==============================================
with open("ga_lgbm_selected_features.pkl", "rb") as f:
    best_features = pickle.load(f)

print(f"✅ Using {len(best_features)} hybrid-selected features:")
print(best_features)

# ==============================================
# 2️⃣ Subset dataset (MULTICLASS)
# ==============================================
feature_cols = df.drop(columns=['label', 'attack_cat']).columns.tolist()

X_final = pd.DataFrame(
    X_scaled,
    columns=feature_cols
)[best_features]

y_final = y_multi.copy()   # multiclass labels

# ==============================================
# 3️⃣ Train-test split (stratified)
# ==============================================
X_train, X_test, y_train, y_test = train_test_split(
    X_final,
    y_final,
    test_size=0.2,
    stratify=y_final,
    random_state=42
)

# ==============================================
# 4️⃣ Train Random Forest (Multiclass)
# ==============================================
print("\n🌳 Training Random Forest (Multiclass)...")

rf = RandomForestClassifier(
    n_estimators=400,
    max_depth=25,
    min_samples_split=4,
    min_samples_leaf=2,
    class_weight="balanced",   # VERY important for IDS
    n_jobs=-1,
    random_state=42
)

rf.fit(X_train, y_train)

# ==============================================
# 5️⃣ Evaluation
# ==============================================
rf_pred = rf.predict(X_test)

rf_acc = accuracy_score(y_test, rf_pred)

print(f"\n✅ RF Multiclass Accuracy: {rf_acc:.4f}")
print("\n📊 RF Classification Report:\n")
print(classification_report(y_test, rf_pred, digits=4))
# ==============================================
# 6️⃣ Confusion Matrix (Blue–White)
# ==============================================
cm = confusion_matrix(y_test, rf_pred)

plt.figure(figsize=(10, 8))
sns.heatmap(
    cm,
    cmap="Blues",          # Blue–white format
    annot=True,
    fmt="d",
    linewidths=0.5,
    cbar=True
)

plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix — Random Forest (Multiclass)")
plt.tight_layout()
plt.show()

# ==============================================
# 6️⃣ Save Model
# ==============================================
joblib.dump(rf, "rf_UNSWNB15_multiclass_hybrid.pkl")
print("\n💾 Model saved as 'rf_UNSWNB15_multiclass_hybrid.pkl'")

# ==========================================================
# 💡 LIGHTGBM - Binary Classification (Hybrid Feature Set)
# ==========================================================

import pandas as pd
import joblib
import lightgbm as lgb
import pickle
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# -----------------------------
# 1. Load selected features
# -----------------------------
with open("ga_lgbm_selected_features.pkl", "rb") as f:
    best_features = pickle.load(f)

print(f"✅ Using {len(best_features)} selected features for LightGBM.")

# -----------------------------
# 2. Prepare dataset
# -----------------------------
X_final = pd.DataFrame(X_scaled, columns=df.drop(columns=['label', 'attack_cat']).columns)[best_features]
y_final = y_binary.copy()  # 0 = Benign, 1 = Attack

# -----------------------------
# 3. Train-test split
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_final, y_final, test_size=0.2, random_state=42, stratify=y_final
)

# -----------------------------
# 4. Train LightGBM
# -----------------------------
print("🚀 Training LightGBM on optimized features...")

params = {
    'objective': 'binary',
    'boosting_type': 'gbdt',
    'metric': 'binary_logloss',
    'num_leaves': 64,
    'learning_rate': 0.05,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'n_jobs': -1,
    'verbose': -1
}

train_data = lgb.Dataset(X_train, label=y_train)
valid_data = lgb.Dataset(X_test, label=y_test, reference=train_data)

# ✅ Use callback-based early stopping for compatibility
callbacks = [lgb.early_stopping(stopping_rounds=30), lgb.log_evaluation(20)]

lgb_model = lgb.train(
    params,
    train_data,
    num_boost_round=300,
    valid_sets=[valid_data],
    callbacks=callbacks
)

# -----------------------------
# 5. Evaluate Model
# -----------------------------
y_pred_prob = lgb_model.predict(X_test, num_iteration=lgb_model.best_iteration)
y_pred = (y_pred_prob > 0.5).astype(int)

acc = accuracy_score(y_test, y_pred)
print(f"\n✅ LightGBM Binary Accuracy: {acc:.4f}")
print("\n📊 Classification Report:\n", classification_report(y_test, y_pred, target_names=['Benign', 'Attack']))

# -----------------------------
# 6. Save Model
# -----------------------------
joblib.dump(lgb_model, "lgbm_UNSWNB15_hybrid.pkl")
print("\n💾 Model saved as 'lgbm_UNSWNB15_hybrid.pkl'")

# ==========================================================
# LIGHTGBM — MULTICLASS TRAINING (Hybrid Selected Features)
# ==========================================================

import pandas as pd
import numpy as np
import lightgbm as lgb
import joblib
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import pickle
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1. Load dataset & features
# -----------------------------
# Ensure your preprocessed DataFrame (df) and scaled features (X_scaled) exist
# df should contain 'attack_cat' and 'label' columns

# If needed, reload df
# df = pd.read_csv("UNSW_NB15_combined.csv")

# Load best (hybrid) features from GA+LightGBM
with open("ga_lgbm_selected_features.pkl", "rb") as f:
    best_features = pickle.load(f)

print(f"✅ Using {len(best_features)} selected features for LightGBM (Multiclass).")

# -----------------------------
# 2. Prepare dataset
# -----------------------------
# Encode multiclass labels
df['attack_cat'] = df['attack_cat'].astype('category')
y = df['attack_cat'].cat.codes  # Convert attack categories to numeric
num_classes = len(y.unique())

# Subset feature matrix
X_final = pd.DataFrame(X_scaled, columns=df.drop(columns=['label', 'attack_cat']).columns)[best_features]
y_final = y.copy()

# -----------------------------
# 3. Split into train/test
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_final, y_final, test_size=0.2, random_state=42, stratify=y_final
)

# -----------------------------
# 4. Prepare LightGBM datasets
# -----------------------------
train_data = lgb.Dataset(X_train, label=y_train)
valid_data = lgb.Dataset(X_test, label=y_test, reference=train_data)

# -----------------------------
# 5. LightGBM Parameters
# -----------------------------
params = {
    'objective': 'multiclass',
    'num_class': num_classes,
    'metric': 'multi_logloss',
    'boosting_type': 'gbdt',
    'num_leaves': 40,
    'learning_rate': 0.05,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'max_depth': 12,
    'random_state': 42,
    'verbose': -1
}

# -----------------------------
# 6. Train LightGBM
# -----------------------------
print("🚀 Training LightGBM (Multiclass)...")

lgb_model = lgb.train(
    params,
    train_data,
    valid_sets=[train_data, valid_data],
    num_boost_round=300,
    callbacks=[lgb.early_stopping(stopping_rounds=20)]
)

# -----------------------------
# 7. Evaluate
# -----------------------------
y_pred = np.argmax(lgb_model.predict(X_test), axis=1)
acc = accuracy_score(y_test, y_pred)

print(f"\n✅ Multiclass LightGBM Accuracy: {acc:.4f}")
print("\n📊 Classification Report:\n", classification_report(y_test, y_pred))

# -----------------------------
# 8. Save Model
# -----------------------------
joblib.dump(lgb_model, "lgbm_UNSWNB15_multiclass.pkl")
print("\n💾 Model saved as 'lgbm_UNSWNB15_multiclass.pkl'")

# ==========================================================
# FINAL MODEL: COST-SENSITIVE LIGHTGBM (MULTICLASS)
# Fixes low recall/precision for minority classes (0,1,9)
# ==========================================================

import pandas as pd
import numpy as np
import lightgbm as lgb
import joblib
import pickle
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.utils.class_weight import compute_class_weight
import warnings
warnings.filterwarnings("ignore")

# ----------------------------------------------------------
# 1. Load selected features (GA + LightGBM)
# ----------------------------------------------------------
with open("ga_lgbm_selected_features.pkl", "rb") as f:
    best_features = pickle.load(f)

print(f"✅ Using {len(best_features)} selected features")

# ----------------------------------------------------------
# 2. Prepare dataset
# ----------------------------------------------------------
X = pd.DataFrame(
    X_scaled,
    columns=df.drop(columns=['label', 'attack_cat']).columns
)[best_features]

# Encode multiclass labels
df['attack_cat'] = df['attack_cat'].astype('category')
y = df['attack_cat'].cat.codes
num_classes = len(np.unique(y))

# ----------------------------------------------------------
# 3. Train-test split
# ----------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# ----------------------------------------------------------
# 4. Compute class weights (CRITICAL STEP)
# ----------------------------------------------------------
classes = np.unique(y_train)
weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weight_dict = dict(zip(classes, weights))
sample_weights = y_train.map(class_weight_dict)

print("⚖️ Class Weights:", class_weight_dict)

# ----------------------------------------------------------
# 5. LightGBM datasets
# ----------------------------------------------------------
train_data = lgb.Dataset(
    X_train,
    label=y_train,
    weight=sample_weights
)

valid_data = lgb.Dataset(
    X_test,
    label=y_test,
    reference=train_data
)

# ----------------------------------------------------------
# 6. LightGBM parameters (STABLE + ACCURATE)
# ----------------------------------------------------------
params = {
    'objective': 'multiclass',
    'num_class': num_classes,
    'metric': 'multi_logloss',
    'boosting_type': 'gbdt',
    'num_leaves': 64,
    'max_depth': -1,
    'learning_rate': 0.03,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'lambda_l1': 0.5,
    'lambda_l2': 0.5,
    'random_state': 42,
    'verbose': -1
}

# ----------------------------------------------------------
# 7. Train model
# ----------------------------------------------------------
print("🚀 Training Cost-Sensitive LightGBM...")

model = lgb.train(
    params,
    train_data,
    valid_sets=[valid_data],
    num_boost_round=500,
    callbacks=[lgb.early_stopping(30)]
)

# ----------------------------------------------------------
# 8. Evaluation
# ----------------------------------------------------------
y_pred = np.argmax(model.predict(X_test), axis=1)

acc = accuracy_score(y_test, y_pred)
print(f"\n✅ Final Accuracy: {acc:.4f}")

print("\n📊 Classification Report:\n")
print(classification_report(y_test, y_pred))

# ----------------------------------------------------------
# 9. Confusion Matrix (Blue-White)
# ----------------------------------------------------------
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(10, 8))
plt.imshow(cm, cmap="Blues")
plt.colorbar()
plt.title("Confusion Matrix — Cost-Sensitive LightGBM")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.tight_layout()
plt.show()

# ----------------------------------------------------------
# 10. Save model
# ----------------------------------------------------------
joblib.dump(model, "lgbm_UNSWNB15_multiclass_cost_sensitive.pkl")
print("\n💾 Model saved as 'lgbm_UNSWNB15_multiclass_cost_sensitive.pkl'")

# ==========================================================
# XGBOOST — MULTICLASS TRAINING (Hybrid Features)
# ==========================================================

import pandas as pd
import numpy as np
import xgboost as xgb
import pickle
import joblib
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1. Load selected features
# -----------------------------
with open("ga_lgbm_selected_features.pkl", "rb") as f:
    best_features = pickle.load(f)

print(f"✅ Using {len(best_features)} selected features for XGBoost.")

# -----------------------------
# 2. Prepare dataset
# -----------------------------
# y = multiclass attack_cat (already encoded earlier)
df['attack_cat'] = df['attack_cat'].astype('category')
y = df['attack_cat'].cat.codes
num_classes = len(y.unique())

# Create final feature matrix
feature_cols = df.drop(columns=['label', 'attack_cat']).columns
X_final = pd.DataFrame(X_scaled, columns=feature_cols)[best_features]
y_final = y.copy()

# -----------------------------
# 3. Train-test split
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_final, y_final, test_size=0.2, stratify=y_final, random_state=42
)

# -----------------------------
# 4. Convert to XGBoost DMatrix
# -----------------------------
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest  = xgb.DMatrix(X_test,  label=y_test)

# -----------------------------
# 5. XGBoost Parameters
# -----------------------------
params = {
    'objective': 'multi:softprob',
    'num_class': num_classes,
    'eval_metric': 'mlogloss',
    'eta': 0.05,
    'max_depth': 10,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'min_child_weight': 3,
    'lambda': 2.0,
    'tree_method': 'hist',   # ✅ RAM friendly
    'random_state': 42
}

# -----------------------------
# 6. Train XGBoost
# -----------------------------
print("🚀 Training XGBoost (Multiclass)...")

xgb_model = xgb.train(
    params,
    dtrain,
    num_boost_round=400,
    evals=[(dtrain, 'train'), (dtest, 'valid')],
    early_stopping_rounds=30
)

# -----------------------------
# 7. Prediction & Evaluation
# -----------------------------
y_pred_prob = xgb_model.predict(dtest)
y_pred = np.argmax(y_pred_prob, axis=1)

acc = accuracy_score(y_test, y_pred)

print(f"\n✅ XGBoost Multiclass Accuracy: {acc:.4f}")
print("\n📊 Classification Report:\n", classification_report(y_test, y_pred))

# -----------------------------
# 8. Save the model
# -----------------------------
joblib.dump(xgb_model, "xgb_UNSWNB15_multiclass.pkl")
print("\n💾 Model saved as 'xgb_UNSWNB15_multiclass.pkl'")

# ==========================================================
# XGBOOST — BINARY CLASS TRAINING (Hybrid Selected Features)
# ==========================================================

import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pickle
import joblib
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1. Load hybrid-selected features
# -----------------------------
with open("ga_lgbm_selected_features.pkl", "rb") as f:
    best_features = pickle.load(f)

print(f"✅ Using {len(best_features)} selected features for XGBoost (Binary).")

# -----------------------------
# 2. Prepare dataset
# -----------------------------
X_final = pd.DataFrame(
    X_scaled,
    columns=df.drop(columns=['label', 'attack_cat']).columns
)[best_features]

y_final = df['label'].copy()  # Binary labels: 0 = Normal, 1 = Attack

# -----------------------------
# 3. Train-test split
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_final, y_final, test_size=0.2, stratify=y_final, random_state=42
)

# -----------------------------
# 4. Define XGBoost parameters (RAM-friendly)
# -----------------------------
params = {
    "objective": "binary:logistic",
    "eval_metric": "logloss",
    "eta": 0.06,
    "max_depth": 10,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "tree_method": "hist",   # ✅ faster + low memory
    "random_state": 42
}

# Convert to DMatrix
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest  = xgb.DMatrix(X_test, label=y_test)

# -----------------------------
# 5. Train XGBoost
# -----------------------------
print("🚀 Training XGBoost (Binary)...")

model = xgb.train(
    params,
    dtrain,
    num_boost_round=300,
    evals=[(dtest, "validation")],
    early_stopping_rounds=20,
    verbose_eval=False
)

# -----------------------------
# 6. Predictions and Evaluation
# -----------------------------
y_pred_prob = model.predict(dtest)
y_pred = (y_pred_prob > 0.5).astype(int)

acc = accuracy_score(y_test, y_pred)
print(f"\n✅ XGBoost Binary Accuracy: {acc:.4f}")
print("\n📊 Classification Report:\n", classification_report(y_test, y_pred))
print("\n🧾 Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# -----------------------------
# 7. Save model
# -----------------------------
model.save_model("xgboost_UNSWNB15_binary.json")
print("\n💾 Model saved as 'xgboost_UNSWNB15_binary.json'")

!pip install catboost

# ==========================================================
# CATBOOST — BINARY CLASS TRAINING (Hybrid Selected Features)
# ==========================================================

import pandas as pd
import numpy as np
from catboost import CatBoostClassifier, Pool
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pickle, joblib, warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1. Load selected features
# -----------------------------
with open("ga_lgbm_selected_features.pkl", "rb") as f:
    best_features = pickle.load(f)

print(f"✅ Using {len(best_features)} hybrid-selected features for CatBoost binary training.")
print(best_features)

# -----------------------------
# 2. Prepare Dataset
# -----------------------------
# X_scaled and y_binary should already exist in your workspace
# X_scaled → normalized features
# y_binary → binary labels (0 for Benign, 1 for Attack)

X_final = pd.DataFrame(X_scaled, columns=df.drop(columns=['label', 'attack_cat']).columns)[best_features]
y_final = y_binary.copy()

# -----------------------------
# 3. Train-test Split
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_final, y_final, test_size=0.2, random_state=42, stratify=y_final
)

# -----------------------------
# 4. Define and Train CatBoost
# -----------------------------
print("\n🚀 Training CatBoost Binary Classifier...")

train_pool = Pool(X_train, y_train)
test_pool = Pool(X_test, y_test)

cat_model = CatBoostClassifier(
    iterations=500,
    depth=8,
    learning_rate=0.05,
    loss_function='Logloss',
    eval_metric='Accuracy',
    random_seed=42,
    verbose=100
)

cat_model.fit(train_pool, eval_set=test_pool, use_best_model=True)

# -----------------------------
# 5. Evaluate Model
# -----------------------------
cat_pred = cat_model.predict(X_test)
cat_acc = accuracy_score(y_test, cat_pred)

print(f"\n✅ CatBoost Binary Accuracy: {cat_acc:.4f}")
print("\n📊 Classification Report:\n", classification_report(y_test, cat_pred))

# Optional: Confusion Matrix
print("\n🧩 Confusion Matrix:")
print(confusion_matrix(y_test, cat_pred))

# -----------------------------
# 6. Save Model
# -----------------------------
joblib.dump(cat_model, "catboost_UNSWNB15_binary.pkl")
print("\n💾 Model saved as 'catboost_UNSWNB15_binary.pkl'")

# ==========================================================
# CATBOOST — MULTICLASS TRAINING (Hybrid Selected Features)
# ==========================================================

import pandas as pd
import numpy as np
from catboost import CatBoostClassifier, Pool
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pickle, joblib, warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1. Load selected features
# -----------------------------
with open("ga_lgbm_selected_features.pkl", "rb") as f:
    best_features = pickle.load(f)

print(f"✅ Using {len(best_features)} hybrid-selected features for CatBoost multiclass training.")
print(best_features)

# -----------------------------
# 2. Prepare Dataset
# -----------------------------
# X_scaled → normalized features
# y_multi → multiclass labels (0–9 for UNSW-NB15 attack categories)

X_final = pd.DataFrame(X_scaled, columns=df.drop(columns=['label', 'attack_cat']).columns)[best_features]
y_final = y_multi.copy()  # ensure you have y_multi = df['attack_cat_encoded'] or similar

num_classes = len(np.unique(y_final))
print(f"🧩 Number of classes detected: {num_classes}")

# -----------------------------
# 3. Train-test Split
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_final, y_final, test_size=0.2, random_state=42, stratify=y_final
)

# -----------------------------
# 4. Define and Train CatBoost
# -----------------------------
print("\n🚀 Training CatBoost Multiclass Classifier...")

train_pool = Pool(X_train, y_train)
test_pool = Pool(X_test, y_test)

cat_model = CatBoostClassifier(
    iterations=600,
    depth=10,
    learning_rate=0.05,
    loss_function='MultiClass',
    eval_metric='Accuracy',
    random_seed=42,
    verbose=100
)

cat_model.fit(train_pool, eval_set=test_pool, use_best_model=True)

# -----------------------------
# 5. Evaluate Model
# -----------------------------
cat_pred = cat_model.predict(X_test)
cat_pred = cat_pred.astype(int).flatten()

cat_acc = accuracy_score(y_test, cat_pred)
print(f"\n✅ CatBoost Multiclass Accuracy: {cat_acc:.4f}")
print("\n📊 Classification Report:\n", classification_report(y_test, cat_pred))

# Optional: Confusion Matrix
print("\n🧩 Confusion Matrix:")
print(confusion_matrix(y_test, cat_pred))

# -----------------------------
# 6. Save Model
# -----------------------------
joblib.dump(cat_model, "catboost_UNSWNB15_multiclass.pkl")
print("\n💾 Model saved as 'catboost_UNSWNB15_multiclass.pkl'")