# -*- coding: utf-8 -*-
"""Copy of CIC_18final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hFaSFLn-iyE6rAwVpu_OQx5tS0YL-p4h
"""

# STEP 1: Import Libraries
# ==========================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

import warnings
warnings.filterwarnings('ignore')

# =========================================
# STEP 2: MOUNT GOOGLE DRIVE AND LOAD DATA
# =========================================
from google.colab import drive
import os
import pandas as pd

# Mount Google Drive
drive.mount('/content/drive')

# Path to your dataset folder
data_path = '/content/drive/MyDrive/CIC_18/'

# List all files in the folder
files = os.listdir(data_path)
print("📁 Files in dataset folder:", files)

# Try loading Parquet first
df_list = []
for f in files:
    if f.endswith('.parquet'):
        file_path = os.path.join(data_path, f)
        print("📄 Loading Parquet file:", f)
        temp_df = pd.read_parquet(file_path)
        df_list.append(temp_df)

# If Parquet files are found, combine them
if len(df_list) > 0:
    df = pd.concat(df_list, ignore_index=True)
    print("✅ Loaded Parquet dataset successfully.")
    print("Shape:", df.shape)
    print("🔍 Columns:", df.columns[:10].tolist(), "...")
else:
    # Fall back to CSV if no Parquet found
    csv_files = [f for f in files if f.endswith('.csv')]
    if len(csv_files) == 0:
        raise ValueError("⚠️ No Parquet or CSV files found in the folder.")
    csv_path = os.path.join(data_path, csv_files[0])
    print(f"📄 Loading CSV file: {csv_files[0]}")
    df = pd.read_csv(csv_path)
    print("✅ Loaded CSV dataset successfully.")
    print("Shape:", df.shape)
    print("🔍 Columns:", df.columns[:10].tolist(), "...")

# Check if Label column exists
print("🧪 Checking Label column...")
print(df['Label'].value_counts().sort_index())

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
data['Label'] = label_encoder.fit_transform(data['Label'])

# ✅ Correct class names
class_names = label_encoder.classes_
print("Class Names:", class_names)

class_mapping = {
    1: 'Benign',
    2: 'Bot',
    3: 'Brute Force',
    4: 'DDoS',
    5: 'DoS',
    6: 'FTP-Patator',
    7: 'Infiltration',
    8: 'PortScan',
    9: 'SSH-Patator',
    10: 'Web Attack',
    11: 'Heartbleed'
}

# =========================================
# STEP 3: DATA PREPROCESSING
# =========================================
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

# Make a copy
data = df.copy()

# Drop irrelevant or unnamed columns
data = data.loc[:, ~data.columns.str.contains('^Unnamed')]

# Check for null values
print("🧹 Missing values per column:\n", data.isnull().sum().sort_values(ascending=False).head())

# Drop rows with NaN or fill
data = data.dropna()

# Identify categorical and numeric columns
categorical_cols = data.select_dtypes(include=['object']).columns
numeric_cols = data.select_dtypes(exclude=['object']).columns

print("\nCategorical Columns:", categorical_cols.tolist()[:10], "...")
print("Numeric Columns:", numeric_cols.tolist()[:10], "...")

# Encode categorical columns (LabelEncoder for simplicity)
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    label_encoders[col] = le

# Feature scaling (Z-score normalization)
scaler = StandardScaler()
data[numeric_cols] = scaler.fit_transform(data[numeric_cols])

# Split into features (X) and labels (y)
X = data.drop('Label', axis=1, errors='ignore')
y = data['Label']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("\n✅ Preprocessing completed successfully.")
print("X_train:", X_train.shape, " | X_test:", X_test.shape)
print("Unique labels:", y_train.nunique())

# ===============================================================
# STEP 2 — HYBRID FEATURE SELECTION (FILTER + OPTIMIZED GA)
# ===============================================================

import numpy as np
import pandas as pd
import time, gc, joblib, random, os, warnings
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_selection import mutual_info_classif
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
warnings.filterwarnings('ignore')

# ---------------- CONFIG ----------------
RANDOM_STATE = 42
SUBSAMPLE = 80000          # use subset for speed
FILTER_TOP = 40            # top-k by mutual info
POP_SIZE = 12              # GA population
N_GEN = 12                 # GA generations
MUT_RATE = 0.15            # mutation probability
KNN_FIT_K = 5              # KNN parameter
KNN_FIT_CV = 2             # CV folds
TOP_FINAL = 20             # final top features
SAVE_PATH = "/content/drive/MyDrive/CIC_17"   # adjust if using CIC_18

# ---------------- INPUT ----------------
# Expect: X_scaled, y already loaded from previous step
print("Encoding labels if needed...")
y_arr = np.array(y)
if np.issubdtype(y_arr.dtype, np.floating):
    le = LabelEncoder()
    y_arr = le.fit_transform(y_arr)
    print("Converted float labels to integers.")
print(f"✅ Encoded label classes: {np.unique(y_arr)}\n")

print("Preparing optimized GA data...")

# ✅ Convert X_scaled to DataFrame if needed
if isinstance(X_scaled, np.ndarray):
    X_df = pd.DataFrame(X_scaled, columns=[f"f{i}" for i in range(X_scaled.shape[1])])
else:
    X_df = X_scaled.copy()

feature_names = list(X_df.columns)

# --- Subsample for faster GA ---
rng = np.random.default_rng(RANDOM_STATE)
sel_idx = rng.choice(X_df.shape[0], size=min(SUBSAMPLE, X_df.shape[0]), replace=False)
X_sub_df = X_df.iloc[sel_idx].reset_index(drop=True)
y_sub = y_arr[sel_idx]
X_sub = X_sub_df.values.astype(np.float32)
print(f"Subsampled shape for GA: {X_sub.shape}")

# ===============================================================
# [1] FILTER STAGE — Mutual Information
# ===============================================================
print("\n[1] Filter: mutual information (top {})".format(FILTER_TOP))
mi = mutual_info_classif(X_sub, y_sub, random_state=RANDOM_STATE)
mi_series = pd.Series(mi, index=feature_names)
selected_filter = mi_series.sort_values(ascending=False).head(FILTER_TOP).index.tolist()
print(f"Top-{FILTER_TOP} features:\n{selected_filter}\n")
X_filt = X_sub[:, [feature_names.index(f) for f in selected_filter]].astype(np.float32)

# ===============================================================
# [2] GENETIC ALGORITHM STAGE — Optimized GA
# ===============================================================
print("[2] GA Stage (optimized) — may take ~20 mins...")
random.seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)

def knn_fitness_mask(mask):
    """Fitness function using KNN accuracy."""
    cols = np.where(mask == 1)[0]
    if len(cols) < 2:   # avoid empty or 1-feature subsets
        return 0.0
    Xtmp = X_filt[:, cols]
    knn = KNeighborsClassifier(n_neighbors=KNN_FIT_K)
    try:
        score = cross_val_score(knn, Xtmp, y_sub, cv=KNN_FIT_CV, scoring='accuracy', n_jobs=2).mean()
        return float(score)
    except Exception:
        return 0.0

n_feat = len(selected_filter)
pop = [np.random.randint(0,2,n_feat).astype(np.int8) for _ in range(POP_SIZE)]
best_mask, best_score = None, -1

for g in range(1, N_GEN+1):
    fitness = np.array([knn_fitness_mask(ind) for ind in pop], dtype=np.float32)
    gen_best = fitness.max(); gen_mean = fitness.mean()

    # ✅ Safe normalization to avoid NaN
    if np.all(fitness <= 0) or np.isnan(fitness).any():
        probs = np.ones(POP_SIZE) / POP_SIZE
    else:
        probs = fitness / fitness.sum()

    if gen_best > best_score:
        best_score = gen_best
        best_mask = pop[int(np.argmax(fitness))].copy()

    print(f"Gen {g}/{N_GEN}: best={gen_best:.4f} mean={gen_mean:.4f}")

    # --- Selection, Crossover, Mutation ---
    new_pop = []
    for _ in range(POP_SIZE // 2):
        parents = np.random.choice(range(POP_SIZE), 2, p=probs)
        p1, p2 = pop[parents[0]], pop[parents[1]]
        cx = np.random.randint(1, n_feat - 1)
        c1 = np.concatenate([p1[:cx], p2[cx:]])
        c2 = np.concatenate([p2[:cx], p1[cx:]])
        for c in (c1, c2):
            r = np.random.random(size=c.shape)
            c[r < MUT_RATE] = 1 - c[r < MUT_RATE]
            new_pop.append(c.astype(np.int8))
    pop = new_pop
    gc.collect()

print(f"\n✅ GA done. Best score={best_score:.4f}")
sbm_selected = [selected_filter[i] for i, b in enumerate(best_mask) if b == 1]
print(f"SBM-selected {len(sbm_selected)} features:\n{sbm_selected}")

# ===============================================================
# [3] RANDOM FOREST — Final Feature Ranking
# ===============================================================
print("\n[3] RandomForest ranking on SBM-selected features...")
X_rfr = X_sub_df[sbm_selected].values.astype(np.float32)
rfr = RandomForestClassifier(n_estimators=200, random_state=RANDOM_STATE, n_jobs=2)
rfr.fit(X_rfr, y_sub)
imp = pd.Series(rfr.feature_importances_, index=sbm_selected).sort_values(ascending=False)
final_features = imp.head(TOP_FINAL).index.tolist()
print(f"\n🔥 Final {TOP_FINAL} hybrid-selected features:\n{final_features}")

# ===============================================================
# [4] SAVE RESULTS
# ===============================================================
os.makedirs(SAVE_PATH, exist_ok=True)
joblib.dump(final_features, os.path.join(SAVE_PATH, "final_hybrid_features_OPTGA.pkl"))
print("\n💾 Saved optimized GA feature list to Drive successfully!")

import os, joblib

SAVE_PATH = "/content/drive/MyDrive/CIC_18"
os.makedirs(SAVE_PATH, exist_ok=True)

# assuming final_features contains your last 20 selected feature names
joblib.dump(final_features, os.path.join(SAVE_PATH, "final_hybrid_features_OPTGA.pkl"))
print("\n💾 Saved optimized GA feature list to Drive successfully!")

# =========================================
# STEP 3 — SMOTE Balancing for CIC_18
# =========================================
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
import joblib, os

SAVE_PATH = "/content/drive/MyDrive/CIC_18"

# --- Load dataset ---
df = pd.read_csv(os.path.join(SAVE_PATH, "cleaned_ids2018_sampled.csv"))
print("✅ Loaded CIC_18 dataset:", df.shape)

# --- Load hybrid-selected features ---
final_features = joblib.load(os.path.join(SAVE_PATH, "final_hybrid_features_OPTGA.pkl"))
print("✅ Loaded hybrid feature list:", len(final_features))

# --- Check and define label column ---
label_col = "Label"
if label_col not in df.columns:
    print("⚠️ Label column not found. Check columns:\n", df.columns.tolist())
    raise KeyError("Label column missing!")

# --- Split into X and y ---
X = df[final_features]
y = df[label_col]

# --- Train-test split ---
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, stratify=y, random_state=42
)
print(f"\nTrain: {X_train.shape}, Test: {X_test.shape}")
print("Before SMOTE class distribution:\n", y_train.value_counts().to_dict())

# --- Apply SMOTE ---
print("\n🌀 Applying SMOTE oversampling (this may take a few minutes)...")
sm = SMOTE(random_state=42, sampling_strategy='auto', k_neighbors=3)
X_res, y_res = sm.fit_resample(X_train, y_train)

print("\n✅ After SMOTE:")
print("Resampled shape:", X_res.shape)
print("Balanced classes:\n", pd.Series(y_res).value_counts().to_dict())

# --- Save SMOTE data ---
np.savez_compressed(os.path.join(SAVE_PATH, "smote_train_cic18.npz"),
                    X_train=X_res, y_train=y_res)
np.savez_compressed(os.path.join(SAVE_PATH, "smote_test_cic18.npz"),
                    X_test=X_test, y_test=y_test)

print("\n💾 Saved balanced data to Drive:")
print(" - smote_train_cic18.npz")
print(" - smote_test_cic18.npz")

import numpy as np

# 📂 Path where your CIC_18 SMOTE-balanced data is saved
SAVE_PATH = "/content/drive/MyDrive/CIC_18"

# 🔹 Load SMOTE-balanced data
data = np.load(f"{SAVE_PATH}/smote_train_cic18.npz", allow_pickle=True)
X_res, y_res = data["X_train"], data["y_train"]

print("✅ Loaded SMOTE-balanced CIC_18 data:", X_res.shape, y_res.shape)

# 🧠 Sample only 10% of SMOTE data to reduce RAM usage
rng = np.random.default_rng(42)
subset_idx = rng.choice(X_res.shape[0], size=int(0.1 * X_res.shape[0]), replace=False)
X_res, y_res = X_res[subset_idx], y_res[subset_idx]

print("✅ Subsampled 10% CIC_18 SMOTE data:", X_res.shape, y_res.shape)

# 💾 Save this smaller subset for faster training
np.savez_compressed(f"{SAVE_PATH}/smote_train_10pct_cic18.npz",
                    X_train=X_res, y_train=y_res)

print(f"💾 Saved 10% subset to: {SAVE_PATH}/smote_train_10pct_cic18.npz")

# ===============================================================
# 🧠 RANDOM FOREST MODEL — CIC_18 (10% SMOTE)
# ===============================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report,
    accuracy_score,
    confusion_matrix,
    ConfusionMatrixDisplay
)
from sklearn.model_selection import train_test_split
import joblib, os

SAVE_PATH = "/content/drive/MyDrive/CIC_18"

# ---------------------------------------------------------------
# Load 10% SMOTE-balanced dataset
# ---------------------------------------------------------------
data = np.load(f"{SAVE_PATH}/smote_train_10pct_cic18.npz", allow_pickle=True)
X, y = data["X_train"], data["y_train"]
print("✅ Loaded subset data:", X.shape, y.shape)

# ---------------------------------------------------------------
# Train-test split
# ---------------------------------------------------------------
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# ---------------------------------------------------------------
# Initialize Random Forest
# ---------------------------------------------------------------
rf = RandomForestClassifier(
    n_estimators=150,
    max_depth=25,
    random_state=42,
    n_jobs=-1
)

# ---------------------------------------------------------------
# Train model
# ---------------------------------------------------------------
print("\n🚀 Training Random Forest...")
rf.fit(X_train, y_train)

# ---------------------------------------------------------------
# Predictions
# ---------------------------------------------------------------
y_pred = rf.predict(X_val)

# ---------------------------------------------------------------
# Accuracy & Classification Report
# ---------------------------------------------------------------
print(f"\n✅ RF Accuracy: {accuracy_score(y_val, y_pred):.4f}")
print("\n📊 Classification Report:\n")
print(classification_report(y_val, y_pred))

# ---------------------------------------------------------------
# CONFUSION MATRIX (PAPER-READY)
# ---------------------------------------------------------------

# 👉 Class labels (as used in your dataset)
class_labels = [1,2,3,4,5,6,7,8,9,10,11]

class_names = [
    "Benign",
    "Bot",
    "Brute Force",
    "DDoS",
    "DoS",
    "FTP-BruteForce",
    "Infiltration",
    "PortScan",
    "SSH-Patator",
    "Web Attack",
    "Heartbleed"
]

# Generate confusion matrix
cm = confusion_matrix(
    y_val,
    y_pred,
    labels=class_labels
)

# ---------- FIGURE SETTINGS (IEEE / Springer style) ----------
plt.figure(figsize=(6.5, 6))   # 🔴 SMALL SIZE

im = plt.imshow(cm, cmap="Blues")
plt.colorbar(im, fraction=0.04, pad=0.03)

plt.xticks(
    ticks=np.arange(len(class_names)),
    labels=class_names,
    rotation=45,
    ha="right",
    fontsize=8
)

plt.yticks(
    ticks=np.arange(len(class_names)),
    labels=class_names,
    fontsize=8
)

plt.xlabel("Predicted", fontsize=9)
plt.ylabel("True", fontsize=9)
plt.title("Confusion Matrix – RF (CIC-IDS2018)", fontsize=10)

# Cell annotations
thresh = cm.max() / 2
for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(
            j, i, cm[i, j],
            ha="center", va="center",
            fontsize=7,
            color="white" if cm[i, j] > thresh else "black"
        )

plt.tight_layout(pad=0.4)
plt.show()

# ---------------------------------------------------------------
# Save model
# ---------------------------------------------------------------
rf_path = os.path.join(SAVE_PATH, "rf_cic18_model.pkl")
joblib.dump(rf, rf_path)
print(f"\n💾 Saved RF model: {rf_path}")

# ===============================================================
# 💡 LIGHTGBM MODEL — CIC_18 (10% SMOTE)
# ===============================================================
import numpy as np
import pandas as pd
from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.model_selection import train_test_split
import joblib, os

SAVE_PATH = "/content/drive/MyDrive/CIC_18"

# --- Load 10% SMOTE-balanced dataset ---
data = np.load(f"{SAVE_PATH}/smote_train_10pct_cic18.npz", allow_pickle=True)
X, y = data["X_train"], data["y_train"]
print("✅ Loaded subset data:", X.shape, y.shape)

# --- Train-test split ---
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# --- Initialize model ---
lgbm = LGBMClassifier(
    n_estimators=200,
    max_depth=25,
    num_leaves=40,
    learning_rate=0.05,
    random_state=42,
    n_jobs=-1
)

# --- Train model ---
print("\n🚀 Training LightGBM...")
lgbm.fit(X_train, y_train)

# --- Evaluate ---
y_pred = lgbm.predict(X_val)
print(f"\n✅ LGBM Accuracy: {accuracy_score(y_val, y_pred):.4f}")
print("\nClassification Report:\n", classification_report(y_val, y_pred))

# --- Save model ---
lgbm_path = os.path.join(SAVE_PATH, "lgbm_cic18_model.pkl")
joblib.dump(lgbm, lgbm_path)
print(f"\n💾 Saved LGBM model: {lgbm_path}")

# ==========================================
# TRAIN XGBOOST MODEL FOR CIC_18
# ==========================================
import numpy as np
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import joblib, os

# --- Paths ---
SAVE_PATH = "/content/drive/MyDrive/CIC_18"

# --- Load 10% SMOTE-balanced data ---
data = np.load(f"{SAVE_PATH}/smote_train_10pct_cic18.npz", allow_pickle=True)
X, y = data["X_train"], data["y_train"]
print("✅ Loaded subset data:", X.shape, y.shape)

# --- Encode labels to start from 0 ---
unique_labels = np.unique(y)
label_mapping = {label: idx for idx, label in enumerate(unique_labels)}
y_encoded = np.array([label_mapping[val] for val in y])
print(f"✅ Encoded labels: {label_mapping}")

# --- Split into train-test ---
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

# --- Initialize XGBoost ---
xgb = XGBClassifier(
    n_estimators=250,
    learning_rate=0.1,
    max_depth=8,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    objective="multi:softmax",
    num_class=len(unique_labels),
    tree_method="hist"
)

# --- Train ---
print("\n🚀 Training XGBoost...")
xgb.fit(X_train, y_train)

# --- Evaluate ---
y_pred = xgb.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"\n✅ XGBoost Accuracy: {acc:.4f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# --- Save Model ---
model_path = os.path.join(SAVE_PATH, "xgb_cic18_model.pkl")
joblib.dump(xgb, model_path)
print(f"\n💾 Saved XGBoost model: {model_path}")

!pip install catboost -q

# ===============================================================
# Load SMOTE-balanced subset + Train CatBoost Model
# ===============================================================
import numpy as np
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
import joblib, os

# --- Load saved SMOTE dataset ---
data_path = "/content/drive/MyDrive/CIC_18/smote_train_10pct_cic18.npz"
data = np.load(data_path)
X_resampled, y_resampled = data["X_train"], data["y_train"]

print(f"✅ Loaded SMOTE-balanced data: {X_resampled.shape} {y_resampled.shape}")

# --- Split data ---
X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled, test_size=0.2, random_state=42, stratify=y_resampled
)
print(f"✅ Train/Test Split Done: {X_train.shape}, {X_test.shape}")

# --- Initialize CatBoost ---
cat = CatBoostClassifier(
    iterations=500,
    depth=8,
    learning_rate=0.05,
    loss_function='MultiClass',
    eval_metric='Accuracy',
    random_seed=42,
    verbose=False,
    early_stopping_rounds=50
)

# --- Train ---
print("\n🚀 Training CatBoost...")
cat.fit(X_train, y_train, eval_set=(X_test, y_test), use_best_model=True)

# --- Evaluate ---
y_pred = cat.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"\n✅ CatBoost Accuracy: {acc:.4f}\n")

print("Classification Report:")
print(classification_report(y_test, y_pred))

# --- Save Model ---
SAVE_PATH = "/content/drive/MyDrive/CIC_18"
os.makedirs(SAVE_PATH, exist_ok=True)
model_path = os.path.join(SAVE_PATH, "catboost_cic18_model.pkl")
joblib.dump(cat, model_path)
print(f"\n💾 Saved CatBoost model: {model_path}")

# ===============================================================
# 🧩 ENSEMBLE MODEL — RF + LightGBM + XGBoost (CIC_18)
# ===============================================================

import joblib
import numpy as np
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import RandomForestClassifier

# --- Path to dataset and saved models ---
SAVE_PATH = "/content/drive/MyDrive/CIC_18"

# --- Load the 10% SMOTE subset ---
data = np.load(f"{SAVE_PATH}/smote_train_10pct_cic18.npz")
X_res, y_res = data["X_train"], data["y_train"]

# --- Train/Test Split ---
X_train, X_test, y_train, y_test = train_test_split(
    X_res, y_res, test_size=0.2, random_state=42, stratify=y_res
)
print(f"✅ Data ready for ensemble — Train: {X_train.shape}, Test: {X_test.shape}")

# ===============================================================
# Load pre-trained base models
# ===============================================================
rf_model = joblib.load(f"{SAVE_PATH}/rf_cic18_model.pkl")
lgbm_model = joblib.load(f"{SAVE_PATH}/lgbm_cic18_model.pkl")
xgb_model = joblib.load(f"{SAVE_PATH}/xgb_cic18_model.pkl")

# --- Optionally print model summary ---
print("\n✅ Loaded base models successfully!")

# ===============================================================
# Create Voting Ensemble
# ===============================================================
ensemble = VotingClassifier(
    estimators=[
        ('rf', rf_model),
        ('lgbm', lgbm_model),
        ('xgb', xgb_model)
    ],
    voting='soft',    # 'soft' = uses predicted probabilities
    n_jobs=-1
)

# ===============================================================
# Train Ensemble (fine-tunes internal probabilities)
# ===============================================================
print("\n🚀 Training Ensemble (RF + LGBM + XGB)...")
ensemble.fit(X_train, y_train)

# ===============================================================
# Evaluate
# ===============================================================
y_pred = ensemble.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print(f"\n✅ Ensemble Accuracy: {acc:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
# CONFUSION MATRIX (PAPER-READY)
# ---------------------------------------------------------------

# 👉 Class labels (as used in your dataset)
class_labels = [1,2,3,4,5,6,7,8,9,10,11]

class_names = [
    "Benign",
    "Bot",
    "Brute Force",
    "DDoS",
    "DoS",
    "FTP-BruteForce",
    "Infiltration",
    "PortScan",
    "SSH-Patator",
    "Web Attack",
    "Heartbleed"
]

# Generate confusion matrix
cm = confusion_matrix(
    y_val,
    y_pred,
    labels=class_labels
)

# ---------- FIGURE SETTINGS (IEEE / Springer style) ----------
plt.figure(figsize=(6.5, 6))   # 🔴 SMALL SIZE

im = plt.imshow(cm, cmap="Blues")
plt.colorbar(im, fraction=0.04, pad=0.03)

plt.xticks(
    ticks=np.arange(len(class_names)),
    labels=class_names,
    rotation=45,
    ha="right",
    fontsize=8
)

plt.yticks(
    ticks=np.arange(len(class_names)),
    labels=class_names,
    fontsize=8
)

plt.xlabel("Predicted", fontsize=9)
plt.ylabel("True", fontsize=9)
plt.title("Confusion Matrix – RF (CIC-IDS2018)", fontsize=10)

# Cell annotations
thresh = cm.max() / 2
for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(
            j, i, cm[i, j],
            ha="center", va="center",
            fontsize=7,
            color="white" if cm[i, j] > thresh else "black"
        )

plt.tight_layout(pad=0.4)
plt.show()

# ===============================================================
# Save Model
# ===============================================================
ensemble_path = f"{SAVE_PATH}/ensemble_voting_rf_lgbm_xgb_cic18.pkl"
joblib.dump(ensemble, ensemble_path)

print(f"\n💾 Saved Ensemble model to: {ensemble_path}")